plugins {
    id 'com.gradleup.shadow' version '8.3.0'
}
tasks.build.dependsOn('shadowJar')

repositories {
    mavenCentral()
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    // Compile only dependencies to detect platforms
    compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
    compileOnly "com.velocitypowered:velocity-api:3.3.0-SNAPSHOT"
    
    // HTTP/JSON fetching
    implementation 'com.google.code.gson:gson:2.10.1'
}

shadowJar {
    archiveFileName = 'PkLogin.jar'

    dependencies {
        exclude(dependency('org.slf4j:.*'))
    }
}

processResources {
    def props = [version: project.version]
    inputs.properties props
    filteringCharset 'UTF-8'
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    
    filesMatching(['velocity-plugin.json', 'paper-plugin.yml', 'plugin.yml']) {
        expand props
    }
}
