#  ________  ___  __    ___       ________  ________  ___  ________     
# |\   __  \|\  \|\  \ |\  \     |\   __  \|\   ____\|\  \|\   ___  \  
# \ \  \|\  \ \  \/  /|\ \  \    \ \  \|\  \ \  \___|\ \  \ \  \\ \  \ 
#  \ \   ____\ \   ___  \ \  \    \ \  \\\  \ \  \  __\ \  \ \  \\ \  \ 
#   \ \  \___|\ \  \\ \  \ \  \____\ \  \\\  \ \  \|\  \ \  \ \  \\ \  \
#    \ \__\    \ \__\\ \__\ \_______\ \_______\ \_______\ \__\ \__\\ \__\
#     \|__|     \|__| \|__|\|_______|\|_______|\|_______|\|__|\|__| \|__|

# Official Website: https://www.pumpkiiings.com
# Discord: https://www.pumpkiiings.com/discord

version: "1.1"

Messages:
  Title:
    # Message sent before login
    before-login:
      title: "&a&lDobrodoÃ…Â¡li!"
      subtitle: "&7Koristite: /login <vaÃ…Â¡a lozinka>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent before registration
    before-register:
      title: "&a&lDobrodoÃ…Â¡li!"
      subtitle: "&7Koristite: /register <vaÃ…Â¡a lozinka> <vaÃ…Â¡a lozinka>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent after login
    after-login:
      title: ""
      subtitle: "&aUspeÃ…Â¡no ste se prijavili!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent after register
    after-register:
      title: ""
      subtitle: "&UspeÃ…Â¡no ste se registrovali!"
      delays:
        start: 0
        duration: 60
        end: 6

        bedrock-auto-login:
        title: "&a&lWelcome!"
        subtitle: "&7Logged in as &eBedrock&7."
        delays:
          start: 0
          duration: 30
          end: 6
      premium-auto-login:
        title: "&a&lWelcome!"
        subtitle: "&7Logged in as &6Premium&7."
        delays:
          start: 0
          duration: 30
          end: 6

  delay-kick:
    # Message sent when a user takes a long time to register
    register-kick: "&cPredugo vam je trebalo da se registrujete."

    # Message sent when a user takes a long time to log in
    login-kick: "&cPredugo vam je trebalo da se prijavite."

  successful-operations:
    # Message when a user exchanges their password
    password-changed: "&aVaÃ…Â¡a lozinka je uspeÃ…Â¡no promenjena."

    # Message sent when a user successfully logs
    successful-login: "&aUspeÃ…Â¡no ste se prijavili."

    # Message sent when a user successfully registers
    successful-register: "&aUspeÃ…Â¡no ste registrovani."

    # Message sent when a player successfully disregisters
    unregister-kick: "&cUspeÃ…Â¡no ste se odjavili."

  kick-messages:
    # Message when a player tries to log on to the server with a small difference in the nickname
    nick-already-registered: "&cNe moÃ…Â¾ete da uÃ„â€˜ete sa imenom {0}&r\n&r&cThis korisniÃ„Âko ime je vecÃŒÂ registrovano kao {1}&r\n&r\n&r&cDa biste uÃ…Â¡li, morate koristiti svoje ime bez velikih / malih slova"

    # Message sent when a user misses many times
    failed-many-times: "&cUneli ste netaÃ„Ânu lozinku."

    # Message sent when password entered is incorrect
    incorrect-password: "&cPogreÃ…Â¡na lozinka. Molim vas, pokuÃ…Â¡ajte ponovo."

  error-messages:
    # Message sent when you are already logged in.
    already-login: "&cVecÃŒÂ ste prijavljeni."

    # Message sent when a nickname has already been registered.
    already-registered: "&cOvo ime je vecÃŒÂ registrovano."

    # Message sent when a nickname has not yet been registered.
    not-registered: "&cOvo ime joÃ…Â¡ uvek nije registrovano."

    # Message sent when the entered password is not equal to the second
    passwords-dont-match: "&cLozinke nisu iste."

    # Message sent when a player tries to change password by entering the same password as the current
    password-same-as-old: "&cUnesena lozinka je ista kao i trenutna."

    # Message sent when the password entered is too large
    password-too-large: "&cUnesena lozinka je preduga."

    # Message sent when the password entered is too small
    password-too-small: "&cUnesena lozinka je prekratka."
    insecure-password: "&cYour password is too weak. It must include numbers, uppercase, lowercase, and symbols."
    change-password-enforced: "&cFor security reasons, you must update your password right now using &e/changepassword&c."

    # Message when a player does not possess the required permission
    insufficient-permissions: "&cNemate dozvolu za pokretanje ove komande."

    # Message to kick a player now online
    already-online: "&cOvaj igraÃ„Â je vecÃŒÂ na mreÃ…Â¾i."

    # Message to show that the command cannot be executed via console
    player-command-usage: "&cOva naredba je onemogucÃŒÂena putem konzole."

    # Message shown when the plugin is reloaded.
    plugin-reload-message: "&eDodatna komponenta je uspeÃ…Â¡no ponovo uÃ„Âitana."

    # Message sent when a database operation has not been successfully performed
    database-error: "&cÃ…Â½ao nam je, nismo uspeli da dovrÃ…Â¡imo ovu operaciju. Molim vas, pokuÃ…Â¡ajte ponovo. [SQL FAIL]"

  other-messages:
    # Mensagem enviada para o uso do comando /logar
    message-login: "&eKoristite komandu /login <Lozinka>"

    # Mensagem enviada para o uso do comando /register
    message-register: "&Koristite komandu /register <Lozinka> <Lozinka>"

    # Mensagem enviada para o uso do comando /mudarsenha
    message-changepassword: "&eKoristite komdanu /changepassword <Trenutna Lozinka> <Nova Lozinka>"

    # Message sent to use the /unregister command
    message-unregister: "&eKoristite komandu /unregister <Trenutna Lozinka"

