#  ________  ___  __    ___       ________  ________  ___  ________     
# |\   __  \|\  \|\  \ |\  \     |\   __  \|\   ____\|\  \|\   ___  \  
# \ \  \|\  \ \  \/  /|\ \  \    \ \  \|\  \ \  \___|\ \  \ \  \\ \  \ 
#  \ \   ____\ \   ___  \ \  \    \ \  \\\  \ \  \  __\ \  \ \  \\ \  \ 
#   \ \  \___|\ \  \\ \  \ \  \____\ \  \\\  \ \  \|\  \ \  \ \  \\ \  \
#    \ \__\    \ \__\\ \__\ \_______\ \_______\ \_______\ \__\ \__\\ \__\
#     \|__|     \|__| \|__|\|_______|\|_______|\|_______|\|__|\|__| \|__|

# Official Website: https://www.pumpkiiings.com
# Discord: https://www.pumpkiiings.com/discord

# WARNING: This is a translation made to PkLogin. It will probably be compatible with all features of PkLogin.

# Translation made by neon#9620

version: "1.1"

Messages:
  Title:
    # GiriÅŸ yapmadan Ã¶nce gÃ¶nderilen mesaj.
    before-login:
      title: "&a&lHOÅžGELDÄ°N!"
      subtitle: "&7GiriÅŸ yapmak iÃ§in: /login <ÅŸifre>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # KayÄ±t olmadan Ã¶nce gÃ¶nderilen mesaj.
    before-register:
      title: "&a&lHOÅžGELDÄ°N!"
      subtitle: "&7KayÄ±t olmak iÃ§in: /register <ÅŸifre> <tekrar ÅŸifre>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # GiriÅŸ yaptÄ±ktan sonra gÃ¶nderilen mesaj.
    after-login:
      title: ""
      subtitle: "&aBaÅŸarÄ±yla giriÅŸ yaptÄ±n!"
      delays:
        start: 0
        duration: 60
        end: 6
    # KayÄ±t olduktan sonra gÃ¶nderilen mesaj.
    after-register:
      title: ""
      subtitle: "&aBaÅŸarÄ±yla kayÄ±t oldun!"
      delays:
        start: 0
        duration: 60
        end: 6
    # YanlÄ±ÅŸ bir ÅŸifre yazÄ±nca gÃ¶nderilen mesaj.
    incorrect-password:
      title: ""
      subtitle: "&cYazdÄ±ÄŸÄ±n ÅŸifre yanlÄ±ÅŸ!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Daha Ã¶nce giriÅŸ yapÄ±p giriÅŸ yapmayÄ± deneyen kullanÄ±cÄ±ya gÃ¶nderilen mesaj.
    already-login:
      title: ""
      subtitle: "&cDaha Ã¶nce giriÅŸ yaptÄ±n!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Daha Ã¶nce kayÄ±t olup kayÄ±t olmayÄ± deneyen kullanÄ±cÄ±ya gÃ¶nderilen mesaj.
    already-registered:
      title: ""
      subtitle: "&cDaha Ã¶nce kayÄ±t oldun!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Åžifreler aynÄ± olmayÄ±nca gÃ¶nderilen mesaj.
    passwords-dont-match:
      title: ""
      subtitle: "&cÅžifreler aynÄ± deÄŸil!"
      delays:
        start: 0
        duration: 60
        end: 6
    # GiriÅŸ yapma sÃ¼resi dolunca gÃ¶nderilen mesaj.
    session-login:
      title: ""
      subtitle: "&eGiriÅŸ yapma sÃ¼ren doldu."
      delays:
        start: 0
        duration: 60
        end: 6
    # Premium (orjinal) hesap Ã¼zerinden sunucuya otomatik giriÅŸ yapÄ±nca gÃ¶nderilen mesaj.
    premium-login:
      title: ""
      subtitle: "&eHesabÄ±nÄ±z orjinal, otomatik giriÅŸ yapÄ±ldÄ±."
      delays:
        start: 0
        duration: 60
        end: 6
    # Eklenti yeniden yÃ¼klenince gÃ¶nderilen mesaj.
    plugin-reload:
      title: ""
      subtitle: "&aKonfigÃ¼rasyon ve dil dosyalarÄ± yenilendi."
      delays:
        start: 0
        duration: 60
        end: 6
    # Yedekleme iÅŸlemi baÅŸarÄ±yla bittiÄŸinde gÃ¶nderilen mesaj.
    backup:
      title: ""
      subtitle: "&aYedekleme baÅŸarÄ±yla gerÃ§ekleÅŸtirildi."
      delays:
        start: 0
        duration: 90
        end: 6
    # Yedekleme iÅŸleminde hata olunca gÃ¶nderilen mesaj.
    backup-error:
      title: ""
      subtitle: "&cYedekleme yapÄ±lamÄ±yor."
      delays:
        start: 0
        duration: 90
        end: 6
    # GÃ¼venlik uyarÄ±sÄ± sohbete gÃ¶nderilince gÃ¶nderilen mesaj.
    security-warning:
      title: ""
      subtitle: "&cSohbette yeni bir gÃ¼venlik uyarÄ±sÄ± gÃ¶nderildi."
      delays:
        start: 0
        duration: 60
        end: 6

  action-bar:
    # GiriÅŸ yapmadan Ã¶nce oyunculara gÃ¶nderilen mesaj (singular).
    singular: "&c{KayÄ±t olmana/giriÅŸ yapmana} {0} saniye kaldÄ±."

    # GiriÅŸ yapmadan Ã¶nce oyunculara gÃ¶nderilen mesaj (plural).
    plural: "&c{KayÄ±t olmana/giriÅŸ yapmana}{0} saniye kaldÄ±."

        bedrock-auto-login:
        title: "&a&lWelcome!"
        subtitle: "&7Logged in as &eBedrock&7."
        delays:
          start: 0
          duration: 30
          end: 6
      premium-auto-login:
        title: "&a&lWelcome!"
        subtitle: "&7Logged in as &6Premium&7."
        delays:
          start: 0
          duration: 30
          end: 6

  delay-kick:
    # Oyuncu uzun sÃ¼re kayÄ±t olmayÄ±nca oyundan atÄ±ldÄ±ÄŸÄ±nda yazan mesaj.
    register-kick: "&cKayÄ±t olmak iÃ§in zamanÄ±n doldu."

    # Oyuncu uzun sÃ¼re giriÅŸ yapmayÄ±nca oyundan atÄ±ldÄ±ÄŸÄ±nda yazan mesaj.
    login-kick: "&cGiriÅŸ yapman Ã§ok uzun sÃ¼rdÃ¼."

  successful-operations:
    # Oyuncu baÅŸarÄ±yla ÅŸifresini deÄŸiÅŸtirdiÄŸinde gÃ¶nderilen mesaj.
    password-changed: "&aÅžifren baÅŸarÄ±yla deÄŸiÅŸtirildi."

    # Oyuncu baÅŸarÄ±yla giriÅŸ yaptÄ±ÄŸÄ±nda gÃ¶nderilen mesaj.
    successful-login: "&aBaÅŸarÄ±yla giriÅŸ yaptÄ±n."

    # Premium (orjinal) hesap ile hesaba girince gÃ¶nderilen mesaj.
    successful-premium-login: "&aOrjinal bir hesap kullandÄ±ÄŸÄ±n iÃ§in otomatik olarak giriÅŸ yaptÄ±n."

    # AynÄ± ip adresi Ã¼zerinden otomatik giriÅŸ yapÄ±lÄ±nca gÃ¶nderilen mesaj
    successful-session-login: "&aOtomatikman giriÅŸ yaptÄ±nÄ±z."

    # Oyuncu baÅŸarÄ±yla kayÄ±t olduÄŸunda gÃ¶nderilen mesaj.
    successful-register: "&aBaÅŸarÄ±yla kayÄ±t oldun."

    # Oyuncu bir yetkili tarafÄ±ndan giriÅŸi yapÄ±lÄ±nca gÃ¶nderilen mesaj.
    forcelogin: "&e{0} isimli kiÅŸinin giriÅŸi tarafÄ±nÄ±zca yapÄ±ldÄ±."

    # Oyuncu kaydÄ±nÄ± kendisi silince gÃ¶nderilen mesaj.
    unregister-kick: "&cKaydÄ±nÄ±zÄ± baÅŸarÄ±yla sildiniz."

    # YapÄ±landÄ±rma iÅŸlemi tamamlanÄ±nca gÃ¶nderilen mesaj.
    config-finished: "&aYapÄ±landÄ±rma tamamlandÄ±."

    # YapÄ±landÄ±rma iÅŸlemi iptal edilince gÃ¶nderilen mesaj.
    config-cancelled: "&cEylem iptal edildi."

  kick-messages:
    # Oyuncu belirli bir takma adÄ± sahip baÅŸka bir oyuncunun ismine yakÄ±n bir isimle oyuna girince gÃ¶nderilen mesaj.
    nick-already-registered: "&cBu takma ad ile oyuna giremezsin {0}&r\n&r&cBu kullanÄ±cÄ± daha Ã¶nce kayÄ±t oldu {1}&r\n&r\n&r&cSunucuya girmek iÃ§in kendi takma adÄ±nÄ± kullanman gerekiyor.BaÅŸkalarÄ±nÄ±n isminde ki harfleri bÃ¼yÃ¼k ve kÃ¼Ã§Ã¼k olarak deÄŸiÅŸtirerek giriÅŸ yapamazsÄ±nÄ±z."

    # Oyuncu Ã§ok fazla yanlÄ±ÅŸ ÅŸifre yazÄ±nca gÃ¶nderilen mesaj.
    failed-many-times: "&cÃ‡ok fazla yanlÄ±ÅŸ ÅŸifre yazdÄ±n."

    # Oyuncu yanlÄ±ÅŸ ÅŸifre yazÄ±nca gÃ¶nderilen mesaj.
    incorrect-password: "&cYanlÄ±ÅŸ ÅŸifre.LÃ¼tfen tekrar deneyin."

    # Oyuncu gÃ¼venlik sistemindeki soruya yanlÄ±ÅŸ cevap verince gÃ¶nderilen mesaj.
    incorrect-answer: "&cYanlÄ±ÅŸ cevap.LÃ¼tfen tekrar deneyin."

    # Sunucu tam aÃ§Ä±lmamÄ±ÅŸken girmeye Ã§alÄ±ÅŸan oyunculara gÃ¶nderilen mesaj.
    wait-server-start: "&cSunucu tamamen aÃ§Ä±lmadÄ±.\n&cBaÄŸlanman iÃ§in biraz bekleyeceksin."

    # ÅžÃ¼pheli eylemleri yÃ¼zÃ¼nden IP adresi engellenen oyuncuya gÃ¶nderilen mesaj.
    account-blocked: "&cIP adresin ÅŸÃ¼pheli eylemler yÃ¼zÃ¼nden engellendi.&r\n&r&cKalan ceza sÃ¼ren: {0}"

    # Oyuncu geÃ§ici ÅŸifresini yanlÄ±ÅŸ yazÄ±nca gÃ¶nderilen mesaj.
    incorrect-temporary-password: "&cGeÃ§iÃ§i ÅŸifre yanlÄ±ÅŸ yazÄ±ldÄ±.LÃ¼tfen tekrar deneyin."

    # Oyuncu geÃ§ersiz bir takma adÄ±yla giriÅŸ yapÄ±nca gÃ¶nderilen mesaj.
    invalid-nickname: "&cTakma adÄ±nÄ±z geÃ§ersiz.BoÅŸluklarÄ±,sembolleri ve geÃ§ersiz karakterleri isminden silip sunucuya girmeyi dene."

    # Premium (orjinal) hesap ile kayÄ±t edilen bir oyuncunun hesabÄ±na korsan hesap ile giriÅŸ yapmayÄ± deneyen kiÅŸiye gÃ¶nderilen mesaj.
    premium-account: "&cÃœzgÃ¼nÃ¼m ama bu hesap bir orjinal hesap tarafÄ±ndan kayÄ±t edildi.&r\n&r&cBu sunucuda oynamak iÃ§in baÅŸka bir takma adÄ± seÃ§.&r\n&r\nEÄŸer bu hesabÄ±n sahibi sizseniz MinecraftÄ± kapatÄ±p aÃ§Ä±n."

  security-messages:
    # Bir oyuncu sezgisel sistem tarafÄ±ndan korunulduÄŸunda gÃ¶nderilen mesaj.
    hacking-attack-warning:
      - ""
      - " &c&lGÃœVENLÄ°K UYARISI"
      - " &cGÃ¼venlik sistemi hesabÄ±nÄ±za olasÄ± bir saldÄ±rÄ± olmasÄ±nÄ± engelledi."
      - " &cÃœÃ§ kez baÅŸarÄ±sÄ±z giriÅŸ yapÄ±ldÄ±."
      - ""
      - " &e&lÄ°PUCU: &eDiÄŸer sunuculardan farklÄ± ÅŸifreler kullan."
      - ""

    # Bir oyuncu sezgisel sistem tarafÄ±ndan birden fazla korunduÄŸunda gÃ¶nderilen mesaj.
    hacking-attack-warning2:
      - ""
      - " &c&lGÃœVENLÄ°K UYARISI"
      - " &cGÃ¼venlik sistemimiz hesabÄ±nÄ±za olasÄ± {0} adet saldÄ±rÄ± olmasÄ±nÄ± engelledi."
      - " &cÃœÃ§ kez baÅŸarÄ±sÄ±z giriÅŸ yapÄ±ldÄ±."
      - ""
      - " &e&lÄ°PUCU: &eDiÄŸer sunuculardan farklÄ± ÅŸifreler kullan."
      - ""

    # Bir oyuncu zayÄ±f bir ÅŸifreyle kayÄ±t olduÄŸunda gÃ¶nderilen mesaj.
    weak-password:
      - ""
      - " &cKayÄ±t olduÄŸunuz ÅŸifre Ã§ok zayÄ±f."
      - " &cHarfler, sayÄ±lar, ve semboller kullanarak gÃ¼venliÄŸini yÃ¼kseltmeni tavsiye ederiz."
      - " &cÃ–rnek ÅŸifre: {0}"
      - ""

    # Oyuncu gÃ¼venlik sorularÄ±nÄ± hesabÄ±na kayÄ±t etmeyince gÃ¶nderilen mesaj..
    security-question-warn-message:
      - ""
      - " &c&lGÃœVENLÄ°K UYARISI"
      - " &7Bu mesaja tÄ±klayÄ±p gÃ¼venlik sorularÄ±nÄ±"
      - " &ckayÄ±t edebilirsin&7.HesabÄ±nÄ±zÄ±n Ã§alÄ±nma"
      - " &7ihtimalini dÃ¼ÅŸÃ¼rÃ¼r"
      - ""

    # Oyuncu gÃ¼venlik sorusu ekleyince gÃ¶nderilen mesaj.
    security-question-add:
      - ""
      - " &e{0}"
      - ""
      - " &7Eylemi iptal etmek iÃ§in ÅŸu komutu kullan &f'cancel' &7."
      - " &7Bu mesaja tÄ±klayarak baÅŸka bir soru oluÅŸturabilirsin."
      - ""

    # Oyuncu gÃ¼venlik sorularÄ±nÄ± doÄŸrularken gÃ¶nderilen mesaj.
    security-question-check:
      - ""
      - " &aDoÄŸrulamadan Ã¶nce bilgilerini kontrol et:"
      - ""
      - " &7{0}: &f'{1}'"
      - ""
      - " &aEÄŸer doÄŸrulamaktan eminsen ÅŸu komutu kullan &f'confirm'&a."
      - " &eEÄŸer bir ÅŸeyi yanlÄ±ÅŸ yazdÄ±ysan ÅŸu komutu kullan &f'repeat'&e."
      - " &cEÄŸer bu eylemi iptal istiyorsan ÅŸu komutu kullan &f'cancel'&c."
      - ""

    # Oyuncudan gÃ¼venlik sorularÄ±nÄ± cevaplamasÄ±nÄ± isteyince gÃ¶nderilen mesaj.
    security-question-request:
      - ""
      - " &aÃœzgÃ¼nÃ¼m, ancak bir kimlik onayÄ± gerekli."
      - " &aSohbette aÅŸaÄŸÄ±daki soruyu cevaplayÄ±n:"
      - ""
      - " &b{0}"
      - ""

    # Oyuncudan gÃ¼venlik sorularÄ± ikinci kez istendiÄŸinde gÃ¶nderilen mesaj.
    security-question-request2:
      - "&aSÄ±radaki soru..."
      - ""
      - " &b{0}"
      - ""

  error-messages:
    # Oyuncu giriÅŸ yapmasÄ±na raÄŸmen tekrar giriÅŸ yapmayÄ± deneyince gÃ¶nderilen mesaj.
    already-login: "&cDaha Ã¶nce giriÅŸ yaptÄ±n."

    # Oyuncu giriÅŸ yapmasÄ±na raÄŸmen bir yetkili oyuncunun hesabÄ±nÄ± komut ile giriÅŸ yapmasÄ±nÄ± saÄŸlamaya Ã§alÄ±ÅŸtÄ±ÄŸÄ±nda gÃ¶nderilen mesaj.
    already-login2: "&cBu oyuncu zaten giriÅŸ yaptÄ±."

    # Daha Ã¶nce kayÄ±t olmuÅŸ bir kiÅŸiye gÃ¶nderilen mesaj.
    already-registered: "&cBu kullanÄ±cÄ± adÄ±na sahip hesap zaten kayÄ±t oldu."

    # KayÄ±t olmayan bir hesap giriÅŸ yapmayÄ± deneyince gÃ¶nderilen mesaj.
    not-registered: "&cBu kullanÄ±cÄ± adÄ±na sahip hesap daha kayÄ±t olmadÄ±."

    # Åžifreler aynÄ± olmayÄ±nca gÃ¶nderilen mesaj.
    passwords-dont-match: "&cÅžifreler aynÄ± deÄŸil."

    # Oyuncu ÅŸifresini doÄŸrulamayÄ±nca gÃ¶nderilen mesaj.
    need-password-confirmation: "&cÅžifreni doÄŸrulaman gerekiyor."

    # Oyuncu geÃ§ici bir ÅŸifre oluÅŸturmayÄ±nca gÃ¶nderilen mesaj.
    no-temporary-password: "&cHenÃ¼z geÃ§ici bir ÅŸifre oluÅŸturulmadÄ±"

    # Oyuncu IP adresinin sÄ±nÄ±rÄ±nÄ± aÅŸÄ±nca gÃ¶nderilen mesaj.
    address-limiter-warning: "&cIP adresinizin sÄ±nÄ±rlarÄ±nÄ± aÅŸtÄ±nÄ±z."

    # Message sent when a player tries to change password by entering the same password as the current.
    password-same-as-old: "&cÅžuandaki ÅŸifrenle aynÄ± ÅŸifreyi girdin."

    # Message sent when the password entered is too large.
    password-too-large: "&cGirdiÄŸin ÅŸifre Ã§ok bÃ¼yÃ¼k."

    # Message sent when the password entered is too small.
    password-too-small: "&cGirdiÄŸin ÅŸifre Ã§ok kÃ¼Ã§Ã¼k."
    insecure-password: "&cYour password is too weak. It must include numbers, uppercase, lowercase, and symbols."
    change-password-enforced: "&cFor security reasons, you must update your password right now using &e/changepassword&c."

    # Bir oyuncu PlugMan / Sistem kullanarak PkLogin'i devre dÄ±ÅŸÄ± bÄ±rakmaya Ã§alÄ±ÅŸtÄ±ÄŸÄ±nda gÃ¶nderilen mesaj.
    plugman-block: "&cBu sunucudaki giriÅŸ eklentisine dokunamazsÄ±n."

    # Message when a player does not possess the required permission.
    insufficient-permissions: "&cBu komutu kullanmak iÃ§in gereken yetkiye sahip deÄŸilsin"

    # Komutun doÄŸru kullanÄ±mÄ±nÄ± gÃ¶stermeyi saÄŸlayan mesaj.
    command-usage: "&cKomutun doÄŸru kullanÄ±mÄ± {0}."

    # Aktif olan kullanÄ±cÄ±yÄ± atmaya Ã§alÄ±ÅŸÄ±nca gÃ¶nderilen mesaj.
    already-online: "&Bu kullanÄ±cÄ± zaten aktif."

    # Oyuncu aktif olmadÄ±ÄŸÄ±nda gÃ¶nderilen hata mesajÄ±.
    offline-error: "&cBu kullanÄ±cÄ± aktif deÄŸil."

    # Komutun konsol Ã¼zeriden kullanÄ±lamayacaÄŸÄ±nÄ± gÃ¶steren mesaj.
    player-command-usage: "&cBu komut konsol Ã¼stÃ¼nden kullanÄ±lamaz."

    # Komutun sadece konsol Ã¼zerinden kullanÄ±labileceÄŸini gÃ¶steren mesaj.
    console-command-usage: "&cBu komut sadece konsoldan kullanÄ±labilir."

    # Eklenti yeniden yÃ¼klendiÄŸinde gÃ¶nderilen mesaj.
    plugin-reload-message: "&eEklenti baÅŸarÄ±yla tekrar yÃ¼klendi."

    # Komutun iÅŸlevi devre dÄ±ÅŸÄ± bÄ±rakÄ±ldÄ±ÄŸÄ±nda gÃ¶nderilen mesaj.
    command-function-disabled: "&eBu komutun iÅŸlevi devre dÄ±ÅŸÄ± bÄ±rakÄ±ldÄ± {0}."

    # VeritabanÄ± iÅŸlemi baÅŸarÄ±yla gerÃ§ekleÅŸtiremediÄŸinde gÃ¶nderilen mesaj.
    database-error: "&cÃœzgÃ¼nÃ¼m, bu iÅŸlemi tamamlayamadÄ±k.LÃ¼tfen tekrar deneyin. [SQL HATASI]"

  other-messages:
    # HÄ±zlÄ±ca giriÅŸ yapmak iÃ§in gÃ¶sterilen mesaj: /login.
    hover-message-login: "&7HÄ±zlÄ±ca giriÅŸ yapmak iÃ§in buraya tÄ±kla."

    # HÄ±zlÄ±ca kayÄ±t olmak iÃ§in gÃ¶sterilen mesaj: /register.
    hover-message-register: "&HÄ±zlÄ±ca kayÄ±t olmak iÃ§in buraya tÄ±kla."

    # Komutun doÄŸru kullanÄ±mÄ±nÄ± gÃ¶steren mesaj: /login
    message-login: "&eGiriÅŸ yapmak iÃ§in &7/login <ÅŸifre>&e."

    # Komutun doÄŸru kullanÄ±mÄ±nÄ± gÃ¶steren mesaj: /register
    message-register: "&eKayÄ±t olmak iÃ§in &7/register <ÅŸifre> <tekrarÅŸifre>&e."

    # Komutun doÄŸru kullanÄ±mÄ±nÄ± gÃ¶steren mesaj: /changepassword
    message-changepassword: "&eÅžifre deÄŸiÅŸtirmek iÃ§in &7/changepassword <ÅŸifren> <yeni ÅŸifren>&e."

    # Komutun doÄŸru kullanÄ±mÄ±nÄ± gÃ¶steren mesaj: /checkprofile
    message-verify: "&Oyuncunun profilini kontrol etmek iÃ§in &7/checkprofile <isim>&e."

    # Komutun doÄŸru kullanÄ±mÄ±nÄ± gÃ¶steren mesaj: /unregister
    message-unregister: "&eKaydÄ±nÄ± silmek iÃ§in &7/unregister <ÅŸifren>&e."
