#  ________  ___  __    ___       ________  ________  ___  ________     
# |\   __  \|\  \|\  \ |\  \     |\   __  \|\   ____\|\  \|\   ___  \  
# \ \  \|\  \ \  \/  /|\ \  \    \ \  \|\  \ \  \___|\ \  \ \  \\ \  \ 
#  \ \   ____\ \   ___  \ \  \    \ \  \\\  \ \  \  __\ \  \ \  \\ \  \ 
#   \ \  \___|\ \  \\ \  \ \  \____\ \  \\\  \ \  \|\  \ \  \ \  \\ \  \
#    \ \__\    \ \__\\ \__\ \_______\ \_______\ \_______\ \__\ \__\\ \__\
#     \|__|     \|__| \|__|\|_______|\|_______|\|_______|\|__|\|__| \|__|

# Official Website: https://www.pumpkiiings.com
# Discord: https://www.pumpkiiings.com/discord

# Argentinean translation made by Gann4

version: "1.1"

Messages:
  Title:
    # Message sent before login
    before-login:
      title: "&a&lÂ¡Bienvenido!"
      subtitle: "&7UsÃ¡: /login <contraseÃ±a>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent before registration
    before-register:
      title: "&a&lÂ¡Bienvenido!"
      subtitle: "&7UsÃ¡: /register <contraseÃ±a> <contraseÃ±a>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent after login
    after-login:
      title: ""
      subtitle: "&aÂ¡Iniciaste sesiÃ³n correctamente!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent after register
    after-register:
      title: ""
      subtitle: "&aÂ¡Te registraste correctamente!"
      delays:
        start: 0
        duration: 60
        end: 6

        bedrock-auto-login:
        title: "&a&lWelcome!"
        subtitle: "&7Logged in as &eBedrock&7."
        delays:
          start: 0
          duration: 30
          end: 6
      premium-auto-login:
        title: "&a&lWelcome!"
        subtitle: "&7Logged in as &6Premium&7."
        delays:
          start: 0
          duration: 30
          end: 6

  delay-kick:
    # Message sent when a user takes a long time to register
    register-kick: "&cTardaste mucho en registrarte."

    # Message sent when a user takes a long time to log in
    login-kick: "&cTardaste mucho en iniciar sesiÃ³n."

  successful-operations:
    # Message when a user exchanges their password
    password-changed: "&aTu contraseÃ±a se cambiÃ³ correctamente."

    # Message sent when a user successfully logs
    successful-login: "&aIniciaste sesiÃ³n correctamente."

    # Message sent when a user successfully registers
    successful-register: "&aTe registraste correctamente."

    # Message sent when a player successfully disregisters
    unregister-kick: "&cCancelaste tu registro correctamente."

  kick-messages:
    # Message when a player tries to log on to the server with a small difference in the nickname
    nick-already-registered: "&cNo podÃ©s registrarte como {0}&r\n&r&cEste nombre de usuario ya se registrÃ³ como {1}&r\n&r\n&r&cPara entrar, tenÃ©s que usar tu nickname sin mayÃºsculas o minÃºsculas."

    # Message sent when a user misses many times
    failed-many-times: "&cIntroduciste una contraseÃ±a incorrecta."

    # Message sent when password entered is incorrect
    incorrect-password: "&cContraseÃ±a incorrecta. Por favor, intenta de nuevo."

  error-messages:
    # Message sent when you are already logged in.
    already-login: "&cYa iniciaste sesiÃ³n."

    # Message sent when a nickname has already been registered.
    already-registered: "&cEste usuario ya estÃ¡ registrado."

    # Message sent when a nickname has not yet been registered.
    not-registered: "&cEste usuario todavÃ­a no estÃ¡ registrado."

    # Message sent when the entered password is not equal to the second
    passwords-dont-match: "&cLas contraseÃ±as no coinciden."

    # Message sent when a player tries to change password by entering the same password as the current
    password-same-as-old: "&cLa nueva contraseÃ±a es igual a la que ya tenÃ©s. Cambiala."

    # Message sent when the password entered is too large
    password-too-large: "&cLa contraseÃ±a es muy larga."

    # Message sent when the password entered is too small
    password-too-small: "&cLa contraseÃ±a es muy corta."
    insecure-password: "&cYour password is too weak. It must include numbers, uppercase, lowercase, and symbols."
    change-password-enforced: "&cFor security reasons, you must update your password right now using &e/changepassword&c."

    # Message when a player does not possess the required permission
    insufficient-permissions: "&cNo tenÃ©s permisos para ejecutar este comando."

    # Message to kick a player now online
    already-online: "&cEste jugador ya estÃ¡ conectado."

    # Message to show that the command cannot be executed via console
    player-command-usage: "&cEste comando se deshabilitÃ³ a travÃ©s de la consola."

    # Message shown when the plugin is reloaded.
    plugin-reload-message: "&eEl plugin se recargÃ³ correctamente."

    # Message sent when a database operation has not been successfully performed
    database-error: "&cLo sentimos, no pudimos completar esta operaciÃ³n. Por favor, intenta de nuevo. [Error SQL]"

  other-messages:
    # Mensagem enviada para o uso do comando /logar
    message-login: "&eUsÃ¡ el comando /login <contraseÃ±a>"

    # Mensagem enviada para o uso do comando /register
    message-register: "&eUsÃ¡ el comando /register <contraseÃ±a> <contraseÃ±a>"

    # Mensagem enviada para o uso do comando /mudarsenha
    message-changepassword: "&eUsÃ¡ el comando /changepassword <contraseÃ±a actual> <contraseÃ±a nueva>"

    # Message sent to use the /unregister command
    message-unregister: "&eUsÃ¡ el comando /unregister <contraseÃ±a actual>"

