#    ___                __  __
#   /___\_ __   ___  /\ \ \/ /  ___   __ _(_)_ __
#  //  // '_ \ / _ \/  \/ / /  / _ \ / _` | | '_ \
# / \_//| |_) |  __/ /\  / /__| (_) | (_| | | | | |
# \___/ | .__/ \___\_\ \/\____/\___/ \__, |_|_| |_|
#       |_|                          |___/

# Official Website: https://www.pumpkiiings.com
# Discord: https://www.pumpkiiings.com/discord

Messages:
  Title:
    # Message sent before login
    before-login:
      title: "&a&lVÍTEJ!"
      subtitle: "&7PouÅ¾ij: /login <heslo>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent before registration
    before-register:
      title: "&a&lVÍTEJ!"
      subtitle: "&7PouÅ¾ij: /register <heslo> <heslo znovu>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent after login
    after-login:
      title: ""
      subtitle: "&aPÅ™ihláÅ¡ení bylo úspÄ›Å¡né!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent after register
    after-register:
      title: ""
      subtitle: "&aRegistrace byla úspÄ›Å¡ná!"
      delays:
        start: 0
        duration: 60
        end: 6

  delay-kick:
    # Message sent when a user takes a long time to register
    register-kick: "&cÄŒas na registraci vyprÅ¡el."

    # Message sent when a user takes a long time to log in
    login-kick: "&cÄŒas na pÅ™ihláÅ¡ení vyprÅ¡el."

  successful-operations:
    # Message when a user exchanges their password
    password-changed: "&aHeslo bylo úspÄ›Å¡nÄ› zmÄ›nÄ›no."

    # Message sent when a user successfully logs
    successful-login: "&aPÅ™ihláÅ¡ení bylo úspÄ›Å¡né."

    # Message sent when a user successfully registers
    successful-register: "&aRegistrace byla úspÄ›Å¡ná."

    # Message sent when a player successfully disregisters
    unregister-kick: "&cZruÅ¡ení registrace bylo úspÄ›Å¡né."

  kick-messages:
    # Message when a player tries to log on to the server with a small difference in the nickname
    nick-already-registered: "&cNelze se pÅ™ihlásit s pÅ™ezdívkou {0}&r\n&r&cToto jméno je jiÅ¾ zaregistrováno jako {1}&r\n&r\n&r&cPro registraci zvol jméno bez velkÃ½ch/malÃ½ch písmen."

    # Message sent when a user misses many times
    failed-many-times: "&cZadáno Å¡patné heslo.."

    # Message sent when password entered is incorrect
    incorrect-password: "&cÅ patné heslo. Zkus to prosím znovu."

  error-messages:
    # Message sent when you are already logged in.
    already-login: "&cJiÅ¾ jsi pÅ™ihláÅ¡en/a."

    # Message sent when a nickname has already been registered.
    already-registered: "&cHráÄ s tímto jménem je jiÅ¾ registrován."

    # Message sent when a nickname has not yet been registered.
    not-registered: "&cHráÄ s tímto jménem nebyl jeÅ¡tÄ› registrován."

    # Message sent when the entered password is not equal to the second
    passwords-dont-match: "&cHesla se neshodují."

    # Message sent when a player tries to change password by entering the same password as the current
    password-same-as-old: "&cNové heslo je shodné se starÃ½m heslem."

    # Message sent when the password entered is too large
    password-too-large: "&cZadané heslo je pÅ™íliÅ¡ dlouhé."

    # Message sent when the password entered is too small
    password-too-small: "&cZadané heslo je pÅ™íliÅ¡ krátké."

    # Message when a player does not possess the required permission
    insufficient-permissions: "&cNa tuto akci nemáÅ¡ práva."

    # Message to kick a player now online
    already-online: "&cTento hráÄ je jiÅ¾ online."

    # Message to show that the command cannot be executed via console
    player-command-usage: "&cPÅ™íkaz byl zablokován konzolí."

    # Message shown when the plugin is reloaded.
    plugin-reload-message: "&ePlugin byl úspÄ›Å¡nÄ› naÄten."

    # Message sent when a database operation has not been successfully performed
    database-error: "&cOmlouváme se, nepodaÅ™ilo se vykonat operaci. Zkuste to znovu. [SQL FAIL]"

  other-messages:
    # Mensagem enviada para o uso do comando /logar
    message-login: "&ePouÅ¾ij pÅ™íkaz /login <heslo>"

    # Mensagem enviada para o uso do comando /register
    message-register: "&ePouÅ¾ij pÅ™íkaz /register <heslo> <heslo znovu>"

    # Mensagem enviada para o uso do comando /mudarsenha
    message-changepassword: "&ePouÅ¾ij pÅ™íkaz /changepassword <aktuální heslo> <nové heslo>"

    # Message sent to use the /unregister command
    message-unregister: "&ePouÅ¾ij pÅ™íkaz /unregister <heslo>"
