#    ___                __  __
#   /___\_ __   ___  /\ \ \/ /  ___   __ _(_)_ __
#  //  // '_ \ / _ \/  \/ / /  / _ \ / _` | | '_ \
# / \_//| |_) |  __/ /\  / /__| (_) | (_| | | | | |
# \___/ | .__/ \___\_\ \/\____/\___/ \__, |_|_| |_|
#       |_|                          |___/

# Official Website: https://www.pumpkiiings.com
# Discord: https://www.pumpkiiings.com/discord

# Polish translation made by Gh77ost#8539 <3
# Fixed by sus town#1347 :}

Messages:
  Title:
    # Message sent before login
    before-login:
      title: "&a&lWitaj!"
      subtitle: "&7Wpisz: /login <hasÅ‚o>"
      delays:
        start: 0
        duration: 120
        end: 6
    # Message sent before registration
    before-register:
      title: "&a&lWitaj!"
      subtitle: "&7Wpisz: /register <hasÅ‚o> <hasÅ‚o>"
      delays:
        start: 0
        duration: 120
        end: 6
    # Message sent after login
    after-login:
      title: "&a&lWeryfikacja!"
      subtitle: "PomyÅ›lnie zalogowano!"
      delays:
        start: 0
        duration: 30
        end: 6
    # Message sent after registration
    after-register:
      title: "&a&lWeryfikacja!"
      subtitle: "PomyÅ›lnie zarejestrowano!"
      delays:
        start: 0
        duration: 30
        end: 6

  delay-kick:
    # Message sent when a user takes a long time to register
    register-kick: "&cMinÄ…Å‚ czas rejestracji."

    # Message sent when a user takes a long time to log in
    login-kick: "&cMinÄ…Å‚ czas logowania."

  successful-operations:
    # Message when a user exchanges their password
    password-changed: "&aTwoje hasÅ‚o zostaÅ‚o zmienione pomyÅ›lnie."

    # Message sent when a user successfully logs
    successful-login: "&aPomyÅ›lnie siÄ™ zalogowaÅ‚eÅ›."

    # Message sent when a user successfully registers
    successful-register: "&aPomyÅ›lnie siÄ™ zarejestrowaÅ‚eÅ›."

    # Message sent when a player successfully disregisters
    unregister-kick: "&cRejestr zostaÅ‚ pomyÅ›lnie usuniÄ™ty."

  kick-messages:
    # Message when a player tries to log on to the server with a small difference in the nickname
    nick-already-registered: "&cNie moÅ¼esz wejÅ›Ä‡ pod tym nickiem {0}\n&cTen uÅ¼ytkownik zostaÅ‚ zarejestrowany jako {1}\n\n&cBy wejÅ›Ä‡ na serwer musisz uÅ¼yÄ‡ starego nicku. ZwróÄ‡ uwagÄ™ na wielkie litery!"

    # Message sent when a user misses many times
    failed-many-times: "&cZbyt wiele razy wpisaÅ‚eÅ› zÅ‚e hasÅ‚o."

    # Message sent when password entered is incorrect
    incorrect-password: "&cNie wÅ‚aÅ›ciwe hasÅ‚o! Spróbuj ponownie."

  error-messages:
    # Message sent when you are already logged in.
    already-login: "&cJesteÅ› juÅ¼ zalogowany."

    # Message sent when a nickname has already been registered.
    already-registered: "&cTen pseudonim zostaÅ‚ juÅ¼ zarejestrowany."

    # Message sent when a nickname has not yet been registered.
    not-registered: "&cTen pseudonim nie zostaÅ‚ jeszcze zarejestrowany."

    # Message sent when the entered password is not equal to the second
    passwords-dont-match: "&cHasÅ‚a nie sÄ… takie same."

    # Message sent when a player tries to change password by entering the same password as the current
    password-same-as-old: "&cWprowadzone hasÅ‚o jest takie samo jak bieÅ¼Ä…ce."

    # Message sent when the password entered is too large
    password-too-large: "&cPodane hasÅ‚o jest za dÅ‚ugie."

    # Message sent when the password entered is too small
    password-too-small: "&cPodane hasÅ‚o jest za krótkie."

    # Message when a player does not possess the required permission
    insufficient-permissions: "&cNie masz uprawnieÅ„ by to zrobiÄ‡."

    # Message to kick a player now online
    already-online: "&cTen gracz jest aktualnie online."

    # Message to show that the command cannot be executed via console
    player-command-usage: "&cTo polecenie nie moÅ¼e zostaÄ‡ wykonane za pomocÄ… konsoli."

    # Message shown when the plugin is reloaded
    plugin-reload-message: "&ePomyÅ›lnie przeÅ‚adowano plugin."

    # Komunikat wysyÅ‚any, gdy operacja na bazie danych nie zostaÅ‚a pomyÅ›lnie wykonana
    database-error: "&cPrzepraszamy, nie mogliÅ›my ukoÅ„czyÄ‡ tej operacji. ProszÄ™ spróbuj ponownie. [SQL FAIL]"

  other-messages:
    # Mensagem enviada para o uso do comando /logar
    message-login: "&eUÅ¼yj polecenia &7/login <hasÅ‚o>&e."

    # Mensagem enviada para o uso do comando /register
    message-register: "&eUÅ¼yj polecenia &7/register <hasÅ‚o> <hasÅ‚o>&e."

    # Mensagem enviada para o uso do comando /mudarsenha
    message-changepassword: "&eUÅ¼yj polecenia &7/changepassword <stare HasÅ‚o> <nowe HasÅ‚o>&e."

    # WiadomoÅ›Ä‡ wysÅ‚ana w celu uÅ¼ycia polecenia /unregister
    message-unregister: "&eUÅ¼yj polecenia &7/unregister <bieÅ¼Ä…ce hasÅ‚o>&e."
