#    ___                __  __
#   /___\_ __   ___  /\ \ \/ /  ___   __ _(_)_ __
#  //  // '_ \ / _ \/  \/ / /  / _ \ / _` | | '_ \
# / \_//| |_) |  __/ /\  / /__| (_) | (_| | | | | |
# \___/ | .__/ \___\_\ \/\____/\___/ \__, |_|_| |_|
#       |_|                          |___/

# ÐžÑ„Ñ–Ñ†Ñ–Ð¹Ð½Ð¸Ð¹ ÑÐ°Ð¹Ñ‚ Ñ€Ð¾Ð·Ñ€Ð¾Ð±Ð½Ð¸ÐºÐ°: https://www.pumpkiiings.com
# Discord: https://www.pumpkiiings.com/discord

# Translation made by @who22

Messages:
  Title:
    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ Ð¿ÐµÑ€ÐµÐ´ Ð²Ñ…Ð¾Ð´Ð¾Ð¼ Ð´Ð¾ ÑÐ¸ÑÑ‚ÐµÐ¼Ð¸
    before-login:
      title: "&a&lÐ’Ñ–Ñ‚Ð°Ñ”Ð¼Ð¾!"
      subtitle: "&7Ð£Ð²Ñ–Ð¹Ð´Ñ–Ñ‚ÑŒ: /login <Ð¿Ð°Ñ€Ð¾Ð»ÑŒ>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑÑ Ð¿ÐµÑ€ÐµÐ´ Ñ€ÐµÐ°Ñ”ÑÑ‚Ñ€Ð°Ñ†Ñ–Ñ”ÑŽ
    before-register:
      title: "&a&lÐ’Ñ–Ñ‚Ð°Ñ”Ð¼Ð¾!"
      subtitle: "&7Ð—Ð°Ñ€ÐµÑ”ÑÑ‚Ñ€ÑƒÐ¹Ñ‚ÐµÑÑ: /register <Ð¿Ð°Ñ€Ð¾Ð»ÑŒ> <Ð¿Ð¾Ð²Ñ‚Ð¾Ñ€ Ð¿Ð°Ñ€Ð¾Ð»ÑŽ>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ Ð¿Ñ–ÑÐ»Ñ ÑƒÑÐ¿Ñ–ÑˆÐ½Ð¾Ð³Ð¾ Ð²Ñ…Ð¾Ð´Ñƒ
    after-login:
      title: ""
      subtitle: "&aÐ’Ð¸ ÑƒÑÐ¿Ñ–ÑˆÐ½Ð¾ ÑƒÐ²Ñ–Ð¹ÑˆÐ»Ð¸!"
      delays:
        start: 0
        duration: 60
        end: 6
    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ Ð¿Ñ–ÑÐ»Ñ ÑƒÑÐ¿Ñ–ÑˆÐ½Ð¾Ñ— Ñ€ÐµÑ”ÑÑ‚Ñ€Ð°Ñ†Ñ–Ñ—
    after-register:
      title: ""
      subtitle: "&aÐ’Ð¸ ÑƒÑÐ¿Ñ–ÑˆÐ½Ð¾ Ð·Ð°Ñ€ÐµÑ”ÑÑ‚Ñ€ÑƒÐ²Ð°Ð»Ð¸ÑÑŒ!"
      delays:
        start: 0
        duration: 60
        end: 6

  delay-kick:
    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ Ð³Ñ€Ð°Ð²ÐµÑ†ÑŒ Ð·Ð°Ð½Ð°Ð´Ñ‚Ð¾ Ð´Ð¾Ð²Ð³Ð¾ Ñ€ÐµÑ”ÑÑ‚Ñ€ÑƒÑ”Ñ‚ÑŒÑÑ
    register-kick: "&cÐ§Ð°Ñ Ñ€ÐµÑ”ÑÑ‚Ñ€Ð°Ñ†Ñ–Ñ— Ð²Ð¸Ñ‡ÐµÑ€Ð¿Ð°Ð½Ð¾."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ Ð³Ñ€Ð°Ð²ÐµÑ†ÑŒ Ð·Ð°Ð½Ð°Ð´Ñ‚Ð¾ Ð´Ð¾Ð²Ð³Ð¾ Ð²Ñ…Ð¾Ð´Ð¸Ñ‚ÑŒ Ð² Ð°ÐºÐ°ÑƒÐ½Ñ‚
    login-kick: "&cÐ’Ð¸ Ð·Ð°Ð½Ð°Ð´Ñ‚Ð¾ Ð´Ð¾Ð²Ð³Ð¾ Ð²Ñ…Ð¾Ð´Ð¸Ð»Ð¸ Ð² Ð°ÐºÐ°ÑƒÐ½Ñ‚."

  successful-operations:
    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ Ð³Ñ€Ð°Ð²ÐµÑ†ÑŒ Ð·Ð¼Ñ–Ð½ÑŽÑ” Ð¿Ð°Ñ€Ð¾Ð»ÑŒ
    password-changed: "&aÐ’Ð°Ñˆ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ ÑƒÑÐ¿Ñ–ÑˆÐ½Ð¾ Ð·Ð¼Ñ–Ð½ÐµÐ½Ð¸Ð¹."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ Ð³Ñ€Ð°Ð²ÐµÑ†ÑŒ Ð²Ñ…Ð¾Ð´Ð¸Ñ‚ÑŒ Ð² Ð°ÐºÐ°ÑƒÐ½Ñ‚
    successful-login: "&aÐ’Ð¸ ÑƒÑÐ¿Ñ–ÑˆÐ½Ð¾ ÑƒÐ²Ñ–Ð¹Ð»Ð¸ Ð² Ð°ÐºÐ°ÑƒÐ½Ñ‚."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ Ð³Ñ€Ð°Ð²ÐµÑ†ÑŒ ÑƒÑÐ¿Ñ–ÑˆÐ½Ð¾ Ñ€ÐµÑ”ÑÑ‚Ñ€ÑƒÑ”Ñ‚ÑŒÑÑ
    successful-register: "&aÐ’Ð¸ ÑƒÑÐ¿Ñ–ÑˆÐ½Ð¾ Ð·Ð°Ñ€ÐµÑ”ÑÑ‚Ñ€ÑƒÐ²Ð°Ð»Ð¸ÑÑŒ."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ Ð³Ñ€Ð°Ð²ÐµÑ†ÑŒ Ð²Ð¸Ð´Ð°Ð»ÑÑ” Ð°ÐºÐ°ÑƒÐ½Ñ‚
    unregister-kick: "&cÐ ÐµÑ”ÑÑ‚Ñ€Ð°Ñ†Ñ–Ñ Ð°ÐºÐ°ÑƒÐ½Ñ‚Ñƒ ÑƒÑÐ¿Ñ–ÑˆÐ½Ð¾ Ð²Ñ–Ð´ÐºÐ»Ð¸ÐºÐ°Ð½Ð°."

  kick-messages:
    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ Ð³Ñ€Ð°Ð²ÐµÑ†ÑŒ Ð½Ð°Ð¼Ð°Ð³Ð°Ñ”Ñ‚ÑŒÑÑ Ð·Ð°Ð¹Ñ‚Ð¸ Ð· Ð½ÐµÐ²ÐµÐ»Ð¸ÐºÐ¾ÑŽ Ñ€Ñ–Ð·Ð½Ð¸Ñ†ÐµÑŽ Ð² Ð½Ñ–ÐºÐ½ÐµÐ¹Ð¼Ñ–
    nick-already-registered: "&cÐ’Ð¸ Ð½Ðµ Ð¼Ð¾Ð¶ÐµÑ‚Ðµ ÑƒÐ²Ñ–Ð¹Ñ‚Ð¸ Ð· Ð½Ñ–ÐºÐ¾Ð¼ {0}&r\n&r&cÐ¦Ðµ Ñ–Ð¼'Ñ ÐºÐ¾Ñ€Ð¸ÑÑ‚ÑƒÐ²Ð°Ñ‡Ð° Ð²ÑÐµ Ð·Ð°Ñ€ÐµÑ”ÑÑ‚Ñ€Ð¾Ð²Ð°Ð½Ð¾ ÑÐº {1}&r\n&r\n&r&cÐ”Ð»Ñ Ð²Ñ…Ð¾Ð´Ñƒ Ð²Ð¸ Ð¿Ð¾Ð²Ð¸Ð½Ð½Ñ– Ð²ÐºÐ°Ð·Ð°Ñ‚Ð¸ Ð½Ñ–ÐºÐ½ÐµÐ¹Ð¼ Ð±ÐµÐ· Ð¿Ñ€Ð¾Ð¿Ð¸ÑÐ½Ð¸Ñ…/Ð´Ñ€ÑƒÐºÐ¾Ð²Ð°Ð½Ð¸Ñ… Ð»Ñ–Ñ‚ÐµÑ€."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ Ð³Ñ€Ð°Ð²ÐµÑ†ÑŒ Ð±Ð°Ð³Ð°Ñ‚Ð¾ Ñ€Ð°Ð·Ñ–Ð² Ð²Ð²Ð¾Ð´Ð¸Ñ‚ÑŒ Ñ…Ð¸Ð±Ð½Ð¸Ð¹ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ
    failed-many-times: "&cÐ’Ñ‹ Ð·Ð°Ð½Ð°Ð´Ñ‚Ð¾ Ð±Ð°Ð³Ð°Ñ‚Ð¾ Ñ€Ð°Ð·Ñ–Ð² Ð²Ð²ÐµÐ»Ð¸ Ñ…Ð¸Ð±Ð½Ð¸Ð¹ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ Ð³Ñ€Ð°Ð²ÐµÑ†ÑŒ Ð²Ð²Ð¾Ð´Ð¸Ñ‚ÑŒ Ñ…Ð¸Ð±Ð½Ð¸Ð¹ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ
    incorrect-password: "&cÐŸÐ°Ñ€Ð¾Ð»ÑŒ Ñ…Ð¸Ð±Ð½Ð¸Ð¹! Ð¡Ð¿Ñ€Ð¾Ð±ÑƒÐ¹Ñ‚Ðµ Ñ‰Ðµ Ñ€Ð°Ð·."

  error-messages:
    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÐºÐ¾Ð»Ð¸ Ð²Ð¸ Ð²Ð¶Ðµ ÑƒÐ²Ñ–Ð¹ÑˆÐ»Ð¸ Ð² ÑÐ¸ÑÑ‚ÐµÐ¼Ñƒ
    already-login: "&cÐ’Ð¸ Ð²Ð¶Ðµ Ð°Ð²Ñ‚Ð¾Ñ€Ð¸Ð·Ð¾Ð²Ð°Ð½Ñ–."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ Ð½Ñ–Ðº Ð²Ð¶Ðµ Ð·Ð°Ñ€ÐµÑ”ÑÑ‚Ñ€Ð¾Ð²Ð°Ð½Ð¸Ð¹
    already-registered: "&cÐ”Ð°Ð½Ðµ Ñ–Ð¼'Ñ ÐºÐ¾Ñ€Ð¸ÑÑ‚ÑƒÐ²Ð°Ñ‡Ð° Ð²Ð¶Ðµ Ð·Ð°Ñ€ÐµÑ”ÑÑ‚Ñ€Ð¾Ð²Ð°Ð½Ðµ."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ Ð½Ñ–Ðº Ñ‰Ðµ Ð½Ðµ Ð·Ð°Ñ€ÐµÑ”ÑÑ‚Ñ€Ð¾Ð²Ð°Ð½Ð¸Ð¹
    not-registered: "&cÐ¦Ðµ Ñ–Ð¼'Ñ ÐºÐ¾Ñ€Ð¸ÑÑ‚ÑƒÐ²Ð°Ñ‡Ð° Ñ‰Ðµ Ð½Ðµ Ð·Ð°Ñ€ÐµÑ”ÑÑ‚Ñ€Ð¾Ð²Ð°Ð½Ðµ."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÐºÐ¾Ð»Ð¸ Ð¿ÐµÑ€ÑˆÐ¸Ð¹ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ Ð½Ðµ ÑÐ¿Ñ–Ð²Ð¿Ð°Ð´Ð°Ñ” Ð· Ð´Ñ€ÑƒÐ³Ð¸Ð¼
    passwords-dont-match: "&cÐŸÐ°Ñ€Ð¾Ð»Ñ– Ð½Ðµ ÑÐ¿Ñ–Ð²Ð¿Ð°Ð´Ð°ÑŽÑ‚ÑŒ."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÐºÐ¾Ð»Ð¸ Ð³Ñ€Ð°Ð²ÐµÑ†ÑŒ Ð½Ð°Ð¼Ð°Ð³Ð°Ñ”Ñ‚ÑŒÑÑ Ð·Ð¼Ñ–Ð½Ð¸Ñ‚Ð¸ ÑÐ²Ñ–Ð¹ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ Ð½Ð° ÑÐ²Ñ–Ð¹ Ñ‚ÐµÐ¿ÐµÑ€Ñ–ÑˆÐ½Ñ–Ð¹
    password-same-as-old: "&cÐ’Ð²ÐµÐ´ÐµÐ½Ð¸Ð¹ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ ÑÐ¿Ñ–Ð²Ð¿Ð°Ð´Ð°Ñ” Ð· Ð²Ð°ÑˆÐ¸Ð¼ Ñ‚ÐµÐ¿ÐµÑ€Ñ–ÑˆÐ½Ñ–Ð¼."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ Ð³Ñ€Ð°Ð²ÐµÑ†ÑŒ Ð²Ð²Ð¾Ð´Ð¸Ñ‚ÑŒ Ð·Ð°Ð½Ð°Ð´Ñ‚Ð¾ Ð´Ð¾Ð²Ð³Ð¸Ð¹ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ
    password-too-large: "&cÐ’Ð¸ Ð²Ð²ÐµÐ»Ð¸ Ð·Ð°Ð½Ð°Ð´Ñ‚Ð¾ Ð´Ð¾Ð²Ð³Ð¸Ð¹ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ Ð³Ñ€Ð°Ð²ÐµÑ†ÑŒ Ð²Ð²Ð¾Ð´Ð¸Ñ‚ÑŒ Ð·Ð°Ð½Ð°Ð´Ñ‚Ð¾ ÐºÐ¾Ñ€Ð¾Ñ‚ÐºÐ¸Ð¹ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ
    password-too-small: "&cÐ’Ð¸ Ð²Ð²ÐµÐ»Ð¸ Ð·Ð°Ð½Ð°Ð´Ñ‚Ð¾ ÐºÐ¾Ñ€Ð¾Ñ‚ÐºÐ¸Ð¹ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ Ñƒ Ð³Ñ€Ð°Ð²Ñ†Ñ Ð½ÐµÐ´Ð¾ÑÑ‚Ð°Ñ‚Ð½ÑŒÐ¾ Ð¿Ñ€Ð°Ð² Ð½Ð° Ð²Ð¸ÐºÐ¾Ð½Ð°Ð½Ð½Ñ ÐºÐ¾Ð¼Ð°Ð½Ð´Ð¸
    insufficient-permissions: "&cÐ£ Ð²Ð°Ñ Ð½ÐµÐ¼Ð°Ñ” Ð¿Ñ€Ð°Ð² Ð½Ð° Ð²Ð¸ÐºÐ¾Ñ€Ð¸ÑÑ‚Ð°Ð½Ð½Ñ Ñ†Ñ–Ñ”Ñ— ÐºÐ¾Ð¼Ð°Ð½Ð´Ð¸."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÐºÐ¾Ð»Ð¸ Ð³Ñ€Ð°Ð²Ñ†Ñ ÐºÑ–ÐºÐ°Ñ” Ð· ÑÐµÑ€Ð²ÐµÑ€Ñƒ Ñ‡ÐµÑ€ÐµÐ· Ð½Ð°ÑÐ²Ð½Ñƒ Ð°ÐºÑ‚Ð¸Ð²Ð½Ñƒ ÑÐµÑÑ–ÑŽ
    already-online: "&cÐ¦ÐµÐ¹ Ð³Ñ€Ð°Ð²ÐµÑ†ÑŒ Ð²Ð¶Ðµ ÑƒÐ²Ñ–Ð¹ÑˆÐ¾Ð² Ð½Ð° ÑÐµÑ€Ð²ÐµÑ€."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ ÐºÐ¾Ð¼Ð°Ð½Ð´Ñƒ Ð½Ðµ Ð¼Ð¾Ð¶Ð½Ð° Ð²Ð¸ÐºÐ¾Ð½Ð°Ñ‚Ð¸ Ð² ÐºÐ¾Ð½ÑÐ¾Ð»Ñ–
    player-command-usage: "&cÐ¦ÑŽ ÐºÐ¾Ð¼Ð°Ð½Ð´Ñƒ Ð½ÐµÐ¼Ð¾Ð¶Ð½Ð° Ð²Ð¸ÐºÐ¾Ñ€Ð¸ÑÑ‚Ð¾Ð²ÑƒÐ²Ð°Ñ‚Ð¸ Ð² ÐºÐ¾Ð½ÑÐ¾Ð»Ñ–."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ Ð¿Ñ–ÑÐ»Ñ Ð¿ÐµÑ€ÐµÐ·Ð°Ð²Ð°Ð½Ñ‚Ð°Ð¶ÐµÐ½Ð½Ñ Ð¿Ð»Ð°Ð³Ñ–Ð½Ñƒ
    plugin-reload-message: "&ePkLogin ÑƒÑÐ¿Ñ–ÑˆÐ½Ð¾ Ð¿ÐµÑ€ÐµÐ·ÐµÐ²Ð°Ð½Ñ‚Ð°Ð¶ÐµÐ½Ð¾."

    # ÐŸÐ¾Ð²Ñ–Ð´Ð¾Ð¼Ð»ÐµÐ½Ð½Ñ Ð²Ñ–Ð´Ð¿Ñ€Ð°Ð²Ð»ÑÑ”Ñ‚ÑŒÑÑ, ÑÐºÑ‰Ð¾ Ð¾Ð¿ÐµÑ€Ð°Ñ†Ñ–Ñ Ð· Ð±Ð°Ð·Ð¾ÑŽ Ð´Ð°Ð½Ð¸Ñ… Ð¿Ñ€Ð¾Ð²Ð°Ð»Ð¸Ð»Ð°ÑÑ
    database-error: "&cÐÐ° Ð¶Ð°Ð»ÑŒ, Ð½Ð°Ð¼ Ð½Ðµ Ð²Ð´Ð°Ð»Ð¾ÑÑ Ð²Ð¸ÐºÐ¾Ð½Ð°Ñ‚Ð¸ Ñ†ÑŽ Ð¾Ð¿ÐµÑ€Ð°Ñ†Ñ–ÑŽ. Ð‘ÑƒÐ´ÑŒ-Ð»Ð°ÑÐºÐ°, ÑÐ¿Ñ€Ð¾Ð±ÑƒÐ¹Ñ‚Ðµ Ñ‰Ðµ Ñ€Ð°Ð·. [SQL FAIL]"

  other-messages:
    # ÐŸÑ–Ð´ÐºÐ°Ð·ÐºÐ° Ð· Ð²Ð¸ÐºÐ¾Ñ€Ð¸ÑÑ‚Ð°Ð½Ð½Ñ ÐºÐ¾Ð¼Ð°Ð½Ð´Ð¸ /login
    message-login: "&eÐ’Ð²ÐµÐ´Ñ–Ñ‚ÑŒ: &7/login <Ð¿Ð°Ñ€Ð¾Ð»ÑŒ>&e."

    # ÐŸÑ–Ð´ÐºÐ°Ð·ÐºÐ° Ð· Ð²Ð¸ÐºÐ¾Ñ€Ð¸ÑÑ‚Ð°Ð½Ð½Ñ ÐºÐ¾Ð¼Ð°Ð½Ð´Ð¸ /register
    message-register: "&eÐ’Ð²ÐµÐ´Ñ–Ñ‚ÑŒ: &7/register <Ð¿Ð°Ñ€Ð¾Ð»ÑŒ> <Ð¿Ð¾Ð²Ñ‚Ð¾Ñ€ Ð¿Ð°Ñ€Ð¾Ð»ÑŽ>&e."

    # ÐŸÑ–Ð´ÐºÐ°Ð·ÐºÐ° Ð· Ð²Ð¸ÐºÐ¾Ñ€Ð¸ÑÑ‚Ð°Ð½Ð½Ñ ÐºÐ¾Ð¼Ð°Ð½Ð´Ð¸ /changepassword
    message-changepassword: "&eÐ’Ð²ÐµÐ´Ñ–Ñ‚ÑŒ: &7/changepassword <Ñ‚ÐµÐ¿ÐµÑ€Ñ–ÑˆÐ½Ñ–Ð¹ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ> <Ð½Ð¾Ð²Ð¸Ð¹ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ>&e."

    # ÐŸÑ–Ð´ÐºÐ°Ð·ÐºÐ° Ð· Ð²Ð¸ÐºÐ¾Ñ€Ð¸ÑÑ‚Ð°Ð½Ð½Ñ ÐºÐ¾Ð¼Ð°Ð½Ð´Ð¸ /unregister
    message-unregister: "&eÐ’Ð¸ÐºÐ¾Ñ€Ð¸ÑÑ‚Ð¾Ð²ÑƒÐ¹Ñ‚Ðµ ÐºÐ¾Ð¼Ð°Ð½Ð´Ñƒ &7/unregister <Ñ‚ÐµÐ¿ÐµÑ€Ñ–ÑˆÐ½Ñ–Ð¹ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ>&e."

