#  ________  ___  __    ___       ________  ________  ___  ________     
# |\   __  \|\  \|\  \ |\  \     |\   __  \|\   ____\|\  \|\   ___  \  
# \ \  \|\  \ \  \/  /|\ \  \    \ \  \|\  \ \  \___|\ \  \ \  \\ \  \ 
#  \ \   ____\ \   ___  \ \  \    \ \  \\\  \ \  \  __\ \  \ \  \\ \  \ 
#   \ \  \___|\ \  \\ \  \ \  \____\ \  \\\  \ \  \|\  \ \  \ \  \\ \  \
#    \ \__\    \ \__\\ \__\ \_______\ \_______\ \_______\ \__\ \__\\ \__\
#     \|__|     \|__| \|__|\|_______|\|_______|\|_______|\|__|\|__| \|__|

# Official Website: https://www.pumpkiiings.com
# Discord: https://www.pumpkiiings.com/discord

# Chinese version (with some small detail change!) translated by SnowCutieOwO
# Contact in SpigotMC: https://www.spigotmc.org/members/snowcutieowo.849243/

version: "1.1"

Messages:
  Title:
    # Message sent before login
    before-login:
      title: "&a&lÃ¦Â¬Â¢Ã¨Â¿Å½!"
      subtitle: "&7Ã¨Â¾â€œÃ¥â€¦Â¥ &a/login <Ã¥Â¯â€ Ã§Â Â> &7Ã¦ÂÂ¥Ã§â„¢Â»Ã¥Â½â€¢!"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent before registration
    before-register:
      title: "&a&lÃ¦Â¬Â¢Ã¨Â¿Å½!"
      subtitle: "&7Ã¨Â¾â€œÃ¥â€¦Â¥ &a/register <Ã¥Â¯â€ Ã§Â Â> <Ã©â€¡ÂÃ¥Â¤ÂÃ¥Â¯â€ Ã§Â Â> &7Ã¦ÂÂ¥Ã¦Â³Â¨Ã¥â€ Å’!"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent after login
    after-login:
      title: ""
      subtitle: "&aÃ¤Â½Â Ã¥Â·Â²Ã¦Ë†ÂÃ¥Å Å¸Ã§â„¢Â»Ã¥Â½â€¢!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent after register
    after-register:
      title: ""
      subtitle: "&aÃ¤Â½Â Ã¥Â·Â²Ã¦Ë†ÂÃ¥Å Å¸Ã¦Â³Â¨Ã¥â€ Å’!"
      delays:
        start: 0
        duration: 60
        end: 6

        bedrock-auto-login:
        title: "&a&lWelcome!"
        subtitle: "&7Logged in as &eBedrock&7."
        delays:
          start: 0
          duration: 30
          end: 6
      premium-auto-login:
        title: "&a&lWelcome!"
        subtitle: "&7Logged in as &6Premium&7."
        delays:
          start: 0
          duration: 30
          end: 6

  delay-kick:
    # Message sent when a user takes a long time to register
    register-kick: "&cÃ¨Â¶â€¦Ã¥â€¡ÂºÃ¦Â³Â¨Ã¥â€ Å’Ã§Â­â€°Ã¥Â¾â€¦Ã¦â€”Â¶Ã©â€”Â´."

    # Message sent when a user takes a long time to log in
    login-kick: "&cÃ¨Â¶â€¦Ã¥â€¡ÂºÃ§â„¢Â»Ã¥Â½â€¢Ã§Â­â€°Ã¥Â¾â€¦Ã¦â€”Â¶Ã©â€”Â´."

  successful-operations:
    # Message when a user exchanges their password
    password-changed: "&aÃ¤Â½Â Ã§Å¡â€žÃ¥Â¯â€ Ã§Â ÂÃ¥Â·Â²Ã¦Ë†ÂÃ¥Å Å¸Ã¦â€ºÂ´Ã¦ÂÂ¢."

    # Message sent when a user successfully logs
    successful-login: "&aÃ¤Â½Â Ã¥Â·Â²Ã¦Ë†ÂÃ¥Å Å¸Ã§â„¢Â»Ã¥Â½â€¢."

    # Message sent when a user successfully registers
    successful-register: "&aÃ¤Â½Â Ã¥Â·Â²Ã¦Ë†ÂÃ¥Å Å¸Ã¦Â³Â¨Ã¥â€ Å’."

    # Message sent when a player successfully disregisters
    unregister-kick: "&cÃ¤Â½Â Ã¥Â·Â²Ã¦Ë†ÂÃ¥Å Å¸Ã§â„¢Â»Ã¥â€¡Âº."

  kick-messages:
    # Message when a player tries to log on to the server with a small difference in the nickname
    nick-already-registered: "&d[Ã¥Â¤Â§Ã¥Â°ÂÃ¥â€ â„¢Ã©ÂªÅ’Ã¨Â¯Â]&r\n&cÃ¤Â½Â Ã¤Â¸ÂÃ¨Æ’Â½Ã¤Â½Â¿Ã§â€Â¨Ã¥ÂÂÃ§Â§Â° &4{0} &cÃ¦ÂÂ¥Ã¦Â³Â¨Ã¥â€ Å’&r\n&r&cÃ¦Â­Â¤Ã§â€Â¨Ã¦Ë†Â·Ã¥ÂÂÃ¥Â·Â²Ã¨Â¢Â«Ã¥ÂÂÃ§Â§Â° &4{1} &cÃ¦Â³Â¨Ã¥â€ Å’&r\n&r\n&r&cÃ¨Â¯Â·Ã¤Â½Â¿Ã§â€Â¨Ã¥ÂÅ½Ã¨â‚¬â€¦Ã¦ÂÂÃ¥Ë†Â°Ã§Å¡â€žÃ§â€Â¨Ã¦Ë†Â·Ã¥ÂÂÃ§â„¢Â»Ã¥â€¦Â¥Ã¦Å“ÂÃ¥Å Â¡Ã¥â„¢Â¨&r\n&d[Ã¥Â¤Â§Ã¥Â°ÂÃ¥â€ â„¢Ã©ÂªÅ’Ã¨Â¯Â]"

    # Message sent when a user misses many times
    failed-many-times: "&cÃ¤Â½Â Ã¨Â¾â€œÃ¥â€¦Â¥Ã¤Âºâ€ Ã©â€â„¢Ã¨Â¯Â¯Ã§Å¡â€žÃ¥Â¯â€ Ã§Â Â."

    # Message sent when password entered is incorrect
    incorrect-password: "&cÃ©â€â„¢Ã¨Â¯Â¯Ã§Å¡â€žÃ¥Â¯â€ Ã§Â Â. &7Ã¨Â¯Â·Ã¨Â¾â€œÃ¥â€¦Â¥Ã¦Â­Â£Ã§Â¡Â®Ã§Å¡â€žÃ¥Â¯â€ Ã§Â Â."

  error-messages:
    # Message sent when you are already logged in.
    already-login: "&cÃ¤Â½Â Ã¥Â·Â²Ã§Â»ÂÃ§â„¢Â»Ã¥Â½â€¢Ã¨Â¿â€¡Ã¤Âºâ€ ."

    # Message sent when a nickname has already been registered.
    already-registered: "&cÃ¦Â­Â¤Ã¥ÂÂÃ§Â§Â°Ã¥Â·Â²Ã¨Â¢Â«Ã¦Â³Â¨Ã¥â€ Å’."

    # Message sent when a nickname has not yet been registered.
    not-registered: "&cÃ¦Â­Â¤Ã¥ÂÂÃ§Â§Â°Ã¨Â¿ËœÃ¦Å“ÂªÃ¨Â¢Â«Ã¦Â³Â¨Ã¥â€ Å’."

    # Message sent when the entered password is not equal to the second
    passwords-dont-match: "&cÃ¥â€°ÂÃ¥ÂÅ½Ã¥Â¯â€ Ã§Â ÂÃ¤Â¸ÂÃ¤Â¸â‚¬Ã¨â€¡Â´."

    # Message sent when a player tries to change password by entering the same password as the current
    password-same-as-old: "&cÃ¦Â­Â¤Ã¥Â¯â€ Ã§Â ÂÃ¤Â¸Å½Ã¦â€”Â§Ã¥Â¯â€ Ã§Â ÂÃ§â€ºÂ¸Ã¥ÂÅ’."

    # Message sent when the password entered is too large
    password-too-large: "&cÃ¥Â¯â€ Ã§Â ÂÃ©â€¢Â¿Ã¥ÂºÂ¦Ã¨Â¿â€¡Ã¥Â¤Â§."

    # Message sent when the password entered is too small
    password-too-small: "&cÃ¥Â¯â€ Ã§Â ÂÃ©â€¢Â¿Ã¥ÂºÂ¦Ã¨Â¿â€¡Ã¥Â°Â."
    insecure-password: "&cYour password is too weak. It must include numbers, uppercase, lowercase, and symbols."
    change-password-enforced: "&cFor security reasons, you must update your password right now using &e/changepassword&c."

    # Message when a player does not possess the required permission
    insufficient-permissions: "&cÃ¤Â½Â Ã¦Â²Â¡Ã¦Å“â€°Ã¤Â½Â¿Ã§â€Â¨Ã¦Â­Â¤Ã¥â€˜Â½Ã¤Â»Â¤Ã§Å¡â€žÃ¦ÂÆ’Ã©â„¢Â."

    # Message to kick a player now online
    already-online: "&cÃ¦Â­Â¤Ã§Å½Â©Ã¥Â®Â¶Ã¥Â·Â²Ã§Â»ÂÃ¥Å“Â¨Ã§ÂºÂ¿."

    # Message to show that the command cannot be executed via console
    player-command-usage: "&cÃ¦Â­Â¤Ã¥â€˜Â½Ã¤Â»Â¤Ã¥ÂÂªÃ¨Æ’Â½Ã¥Å“Â¨Ã¦Å½Â§Ã¥Ë†Â¶Ã¥ÂÂ°Ã¦â€°Â§Ã¨Â¡Å’."

    # Message shown when the plugin is reloaded.
    plugin-reload-message: "&7Ã¦Ââ€™Ã¤Â»Â¶Ã¥Â·Â²Ã¨Â¢Â«&aÃ¦Ë†ÂÃ¥Å Å¸Ã©â€¡ÂÃ¨Â½Â½!"

    # Message sent when a database operation has not been successfully performed
    database-error: "&cÃ¥â€¡ÂºÃ©â€â„¢Ã¤Âºâ€ ! &7Ã¦Ââ€™Ã¤Â»Â¶Ã¨Â¿ÂÃ¨Â¡Å’Ã¨Â¿â€¡Ã§Â¨â€¹Ã¤Â¸Â­Ã¥â€¡ÂºÃ§Å½Â°Ã©â€”Â®Ã©Â¢Ëœ,Ã¨Â¯Â·Ã¦â€ºÂ´Ã¦â€Â¹Ã©â€¦ÂÃ§Â½Â®Ã¦â€“â€¡Ã¤Â»Â¶Ã¥ÂÅ½Ã©â€¡ÂÃ¨Â¯â€¢. &c(Ã©â€â„¢Ã¨Â¯Â¯Ã¥Å½Å¸Ã¥â€ºÂ : Ã¦â€¢Â°Ã¦ÂÂ®Ã¥Âºâ€œÃ¨Â¿Å¾Ã¦Å½Â¥Ã¤Â¸ÂÃ¦Ë†ÂÃ¥Å Å¸)"

  other-messages:
    # Mensagem enviada para o uso do comando /logar
    message-login: "&eÃ¨Â¯Â·Ã¤Â½Â¿Ã§â€Â¨Ã¦Å’â€¡Ã¤Â»Â¤ /login <Ã¥Â¯â€ Ã§Â Â> Ã¦ÂÂ¥Ã§â„¢Â»Ã¥Â½â€¢"

    # Mensagem enviada para o uso do comando /register
    message-register: "&eÃ¨Â¯Â·Ã¤Â½Â¿Ã§â€Â¨Ã¦Å’â€¡Ã¤Â»Â¤ /register <Ã¥Â¯â€ Ã§Â Â> <Ã©â€¡ÂÃ¥Â¤ÂÃ¥Â¯â€ Ã§Â Â> Ã¦ÂÂ¥Ã¦Â³Â¨Ã¥â€ Å’"

    # Mensagem enviada para o uso do comando /mudarsenha
    message-changepassword: "&eÃ¨Â¯Â·Ã¤Â½Â¿Ã§â€Â¨Ã¦Å’â€¡Ã¤Â»Â¤ /changepassword <Ã¥Â½â€œÃ¥â€°ÂÃ¥Â¯â€ Ã§Â Â> <Ã¦â€“Â°Ã¥Â¯â€ Ã§Â Â> Ã¦ÂÂ¥Ã¦â€ºÂ´Ã¦ÂÂ¢Ã¥Â¯â€ Ã§Â Â"

    # Message sent to use the /unregister command
    message-unregister: "&eÃ¨Â¯Â·Ã¤Â½Â¿Ã§â€Â¨Ã¦Å’â€¡Ã¤Â»Â¤ /unregister <Ã¥Â½â€œÃ¥â€°ÂÃ¥Â¯â€ Ã§Â Â> Ã¦ÂÂ¥Ã§â„¢Â»Ã¥â€¡Âº"

