#  ________  ___  __    ___       ________  ________  ___  ________     
# |\   __  \|\  \|\  \ |\  \     |\   __  \|\   ____\|\  \|\   ___  \  
# \ \  \|\  \ \  \/  /|\ \  \    \ \  \|\  \ \  \___|\ \  \ \  \\ \  \ 
#  \ \   ____\ \   ___  \ \  \    \ \  \\\  \ \  \  __\ \  \ \  \\ \  \ 
#   \ \  \___|\ \  \\ \  \ \  \____\ \  \\\  \ \  \|\  \ \  \ \  \\ \  \
#    \ \__\    \ \__\\ \__\ \_______\ \_______\ \_______\ \__\ \__\\ \__\
#     \|__|     \|__| \|__|\|_______|\|_______|\|_______|\|__|\|__| \|__|

# Official Website: https://www.pumpkiiings.com
# Discord: https://www.pumpkiiings.com/discord

# WARNING: This is a translation made to PkLogin. It will probably be compatible with all features of PkLogin.

# Lithuanian translation made by SkirmisLTU (Discord: SkirmisLTU#3310)

version: "1.1"

Messages:
  Title:
    # Message sent before login.
    before-login:
      title: "&a&lSveiki!"
      subtitle: "&7Naudokite: /login <Tavo slaptaÃ…Â¾odis>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent before registration.
    before-register:
      title: "&a&lSveiki!"
      subtitle: "&7Naudokite: /register <SlaptaÃ…Â¾odis> <SlaptaÃ…Â¾odis>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent after login.
    after-login:
      title: ""
      subtitle: "&aJÃ…Â«s sÃ„â€”kmingai prisijungÃ„â€”te!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent after registration.
    after-register:
      title: ""
      subtitle: "&aJÃ…Â«s sÃ„â€”kmingai UÃ…Â¾siregistravote!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when you miss a password.
    incorrect-password:
      title: ""
      subtitle: "&cNeteisingas slaptaÃ…Â¾odis!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when already logged in.
    already-login:
      title: ""
      subtitle: "&cJÃ…Â«s jau prisijungÃ„â„¢s!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when already registered.
    already-registered:
      title: ""
      subtitle: "&cJÃ…Â«s jau prisiregistavÃ„â„¢s!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when passwords are not equal.
    passwords-dont-match:
      title: ""
      subtitle: "&cSlaptaÃ…Â¾odÃ…Â¾iai nesutampa!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when session is continued.
    session-login:
      title: ""
      subtitle: "&eJÃ…Â«sÃ…Â³ prisijungimo sesija yra tÃ„â„¢siama."
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when you are an original player.
    premium-login:
      title: ""
      subtitle: "&eJÃ…Â«sÃ…Â³ paskyra yra unikali, sÃ„â€”kmingai prisijungÃ„â€”te."
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when a login session is continued.
    plugin-reload:
      title: ""
      subtitle: "&aKonfigÃ…Â«racijos ir kalbos failai buvo perkrauti."
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent from backup system.
    backup:
      title: ""
      subtitle: "&aAtsarginÃ„â€” kopija sukurta sÃ„â€”kmingai."
      delays:
        start: 0
        duration: 90
        end: 6
    # Message sent from backup system.
    backup-error:
      title: ""
      subtitle: "&cNeiÃ…Â¡Ã„â€”jo sukurti atsarginÃ„â€”s kopijos."
      delays:
        start: 0
        duration: 90
        end: 6
    # Message sent from security system.
    security-warning:
      title: ""
      subtitle: "&cChat'e iÃ…Â¡siustas naujas saugumo Ã„Â¯spÃ„â€”jimas"
      delays:
        start: 0
        duration: 60
        end: 6

  action-bar:
    # Message sent on the player's actionbar before login (singular).
    singular: "&cJÃ…Â«s turite {0} sekundÃ„â„¢, kad {prisijunktumÃ„â€”te/UÃ…Â¾siregistruotumÃ„â€”te}."

    # Message sent on the player's actionbar before login (plural).
    plural: "&cJÃ…Â«s turite {0} sekundes kad {lprisijunktumÃ„â€”te/UÃ…Â¾soregistruotumÃ„â€”te}."

        bedrock-auto-login:
        title: "&a&lWelcome!"
        subtitle: "&7Logged in as &eBedrock&7."
        delays:
          start: 0
          duration: 30
          end: 6
      premium-auto-login:
        title: "&a&lWelcome!"
        subtitle: "&7Logged in as &6Premium&7."
        delays:
          start: 0
          duration: 30
          end: 6

  delay-kick:
    # Message sent when a user takes a long time to register.
    register-kick: "&cPer ilgai uÃ…Â¾trukote registruodamiesi."

    # Message sent when a user takes a long time to log in.
    login-kick: "&cPer ilgai uÃ…Â¾trukote prisijunkdami."

  successful-operations:
    # Message when a user exchanges their password.
    password-changed: "&aJÃ…Â«sÃ…Â³ slaptaÃ…Â¾odis buvo sÃ„â€”kmingai pakeistas."

    # Message sent when a user successfully logs.
    successful-login: "&aJÃ…Â«s sÃ„â€”kmingai prisijungÃ„â€”te."

    # Message sent when a user logs in with an original account.
    successful-premium-login: "&aJÃ…Â«s esate automatiÃ…Â¡kai prisijungÃ„â„¢s, kai naudojate unikaliÃ„â€¦ paskyrÃ„â€¦."

    # Message sent when a user logs in using the same ip address.
    successful-session-login: "&aJÃ…Â«sÃ…Â³ prisijungimo sesija yra tÃ„â„¢siama."

    # Message sent when a user successfully registers.
    successful-register: "&aJÃ…Â«s sÃ„â€”kmingai uÃ…Â¾siregistravote."

    # Message sent when you force a player's login.
    forcelogin: "&eJÃ…Â«s buvote prijunktas {0}"

    # Message sent when a player successfully unregister.
    unregister-kick: "&cJÃ…Â«s sÃ„â€”kmingai iÃ…Â¡siregistravote."

    # Message sent when a configuration is finished
    config-finished: "&aConfiguracija baigta."

    # Message sent when a configuration is cancelled
    config-cancelled: "&cVeiksmas atÃ…Â¡auktas."

  kick-messages:
    # Message when a player tries to log on to the server with a small difference in the nickname.
    nick-already-registered: "&cJÃ…Â«s negalite Ã„Â¯eiti su slapyvardziu {0}&r\n&r&cdÃ„â€”l to nes Ã…Â¡is slapyvardis jau uÃ…Â¾registruotas kaip {1}&r\n&r\n&r&cKad, Ã„Â¯eiti turite naudoti savo slapyvardÃ„Â¯ be didÃ…Â¾iÃ…Â³jÃ…Â³/maÃ…Â¾Ã…Â³jÃ…Â³ raidÃ…Â¾iÃ…Â³"

    # Message sent when a user misses many times.
    failed-many-times: "&cÃ„Â®vedÃ„â€”te neteisingÃ„â€¦ slaptaÃ…Â¾odÃ„Â¯."

    # Message sent when password entered is incorrect.
    incorrect-password: "&cNeteisingas slaptaÃ…Â¾odis. Bandykite dar kartÃ„â€¦."

    # Message sent when the security questions answer is incorrect.
    incorrect-answer: "&cNeteisingas atsakymas. Bandykite dar kartÃ„â€¦."

    # Message sent when server is still starting.
    wait-server-start: "&cServeris dar nÃ„â€”ra visiÃ…Â¡kai paleistas.\n&cTruputi palaukite, kad prisijunkti."

    # Message sent when an IP is blocked by suspected invasion.
    account-blocked: "&cJÃ…Â«sÃ…Â³ adresas buvo uÃ…Â¾blokuotas dÃ„â€”l Ã„Â¯tariamos invazijos.&r\n&r&cLikÃ„â„¢s uÃ…Â¾blokavimo laikas: {0}"

    # Message sent when two-factor system temporary password is incorrect.
    incorrect-temporary-password: "&cNeteisingas slaptaÃ…Â¾odis.Bandykite dar kartÃ„â€¦."

    # Message to kick a user with an invalid nickname.
    invalid-nickname: "&cJÃ…Â«sÃ…Â³ slapyvardis yra neteisingas, iÃ…Â¡ vardo paÃ…Â¡alinkite tarpus, simbolius ir netinkamus simbolius."

    # Message sent when the player's account has already been registered as unique.
    premium-account: "&cAtsipraÃ…Â¡ome, bet premium vartotojas (nusipirkÃ„â„¢s minecraft) jau prisijungÃ„â€” prie Ã…Â¡ios paskyros.&r\n&r&cNorÃ„â€”dami Ã…Â¾aisti serveryje, turite naudoti kitÃ„â€¦ slapyvardÃ„Â¯.&r\n&r\nJei esate Ã…Â¡ios paskyros savininkas, pabandykite iÃ…Â¡ naujo paleisti Ã¢â‚¬Å¾MinecraftÃ¢â‚¬Å“."

  security-messages:
    # Message sent when a user was protected by the heuristic system.
    hacking-attack-warning:
      - ""
      - " &c&lSAUGUMO Ã„Â®SPÃ„â€“JIMAS"
      - " &cSaugumo sistema uÃ…Â¾blokavo galimas Ã„Â¯silauÃ…Â¾imo atakas jÃ…Â«sÃ…Â³ paskyroje."
      - " &cBuvo bandyta tris kartus nesÃ„â€”kmingai prisijungti."
      - ""
      - " &e&lPATARIMAS: &eNAudokite skirtingus slaptaÃ…Â¾odÃ…Â¾ius skirtinguose serveriuose."

    # Message sent when a user was protected more than once by the heuristic system.
    hacking-attack-warning2:
      - ""
      - " &c&lSAUGUMO Ã„Â®SPÃ„â€“JIMAS"
      - " &cSaugumo sistema uÃ…Â¾blokavo {0} galimas Ã„Â¯silauÃ…Â¾imo atakas jÃ…Â«sÃ…Â³ paskyroje."
      - " &cBuvo bandyta tris kartus nesÃ„â€”kmingai prisijungti."
      - ""
      - " &e&Susisiekite su serverio administatoriais."
      - ""

    # Message sent when a user uses a weak password.
    weak-password:
      - ""
      - " &cUÃ…Â¾registruotas slaptaÃ…Â¾odis laikomas nesaugiu."
      - " &cNorÃ„â€”dami pagerinti saugumÃ„â€¦, naudokite raides, skaiÃ„Âius ir simbolius."
      - " &cSaugaus slaptaÃ…Â¾odÃ…Â¾io pavyzdys: {0}"
      - ""

    # Message sent when a player has not yet registered the security questions.
    security-question-warn-message:
      - ""
      - " &c&lAPSAUGOS KLAUSIMAI"
      - " &7NorÃ„â€”dami uÃ…Â¾siregistruoti, spustelÃ„â€”kite Ã…Â¡Ã„Â¯ praneÃ…Â¡imÃ„â€¦"
      - " &cApsaugos klausimai&7. Tai darydami"
      - " &7sumaÃ…Â¾insite Ã„Â¯silauÃ…Â¾imo tikimybÃ„â„¢."
      - ""

    # Message sent when a security question is being added.
    security-question-add:
      - ""
      - " &e{0}"
      - ""
      - " &7NorÃ„â€”dami atÃ…Â¡aukti operacijÃ„â€¦, Ã„Â¯veskite &f'cancel'."
      - " &7SpustelÃ„â€”kite Ã…Â¡Ã„Â¯ praneÃ…Â¡imÃ„â€¦, kad sugeneruotumÃ„â€”te kitÃ„â€¦ klausimÃ„â€¦."
      - ""

    # Message sent when a security question should be reviewed.
    security-question-check:
      - ""
      - " &aPrieÃ…Â¡ patvirtindami, patikrinkite informacijÃ„â€¦:"
      - ""
      - " &7{0}: &f'{1}'"
      - ""
      - " &aJei esate tikras, Ã„Â¯veskite &f'confirm'&a."
      - " &eJei Ã„Â¯vedÃ„â€”te kaÃ…Â¾kÃ„â€¦ ne taip, Ã„Â¯veskite &f'repeat'&e."
      - " &cJei norite atÃ…Â¡aukti Ã…Â¡iÃ„â€¦ operacijÃ„â€¦, Ã„Â¯veskite &f'cancel'&c."
      - ""

    # Message sent when security questions are requested.
    security-question-request:
      - ""
      - " &aAtsipraÃ…Â¡ome, bet reikalingas tapatybÃ„â€”s patvirtinimas."
      - " &aAtsakykite Ã„Â¯ pateiktÃ„â€¦ klausimÃ„â€¦ chat'e:"
      - ""
      - " &b{0}"
      - ""

    # Message sent when security questions are requested a second time.
    security-question-request2:
      - "&aKitas klausimas..."
      - ""
      - " &b{0}"
      - ""

  error-messages:
    # Message sent when you are already logged in.
    already-login: "&cJÃ…Â«s jau esate prisijungÃ„â„¢s."

    # Message sent when a user is already logged in.
    already-login2: "&cÃ…Â is Ã…Â¾aidÃ„â€”jau jau prisijungÃ„â„¢s."

    # Message sent when a nickname has already been registered.
    already-registered: "&cÃ…Â is slapyvardis jau buvo uÃ…Â¾registruotas."

    # Message sent when a nickname has not yet been registered.
    not-registered: "&cÃ…Â is slapyvardis dar nebuvo uÃ…Â¾registruotas."

    # Message sent when the entered password is not equal to the second.
    passwords-dont-match: "&cSlaptaÃ…Â¾odÃ…Â¾iai nÃ„â€”ra vienodi."

    # Message sent when a player does not confirm your password.
    need-password-confirmation: "&cTurite patvirtinti savo slaptaÃ…Â¾odÃ„Â¯."

    # Message sent when a user does not have a temporary password.
    no-temporary-password: "&cLaikinas slaptaÃ…Â¾odis dar nesugeneruotas."

    # Message sent when IP limits per player pass the limit.
    address-limiter-warning: "&cJÃ…Â«s iÃ…Â¡naudojote Ã…Â¾aidÃ„â€”jÃ…Â³ limitÃ„â€¦ per IP adresÃ„â€¦."

    # Message sent when a player tries to change password by entering the same password as the current.
    password-same-as-old: "&cÃ„Â®vestas slaptaÃ…Â¾odis yra toks pats kaip dabartinis."

    # Message sent when the password entered is too large.
    password-too-large: "&cÃ„Â®vestas slaptaÃ…Â¾odis per ilgas."

    # Message sent when the password entered is too small.
    password-too-small: "&cÃ„Â®vestas slaptaÃ…Â¾odis per trumpas."
    insecure-password: "&cYour password is too weak. It must include numbers, uppercase, lowercase, and symbols."
    change-password-enforced: "&cFor security reasons, you must update your password right now using &e/changepassword&c."

    # Message sent when a user attempts to disable PkLogin using PlugMan/System.
    plugman-block: "&cJÃ…Â«s negalite liesti plugino (naudokite /PkLogin reload)."

    # Message when a player does not possess the required permission.
    insufficient-permissions: "&cJÃ…Â«s neturite leidimo vykdyti Ã…Â¡iÃ„â€¦ komandÃ„â€¦."

    # Message to show the use of a command.
    command-usage: "&cJÃ…Â«s turite naudoti {0}."

    # Message to kick a player now online.
    already-online: "&cÃ…Â is Ã…Â¾aidÃ„â€”jas jau prisijungÃ„â„¢s."

    # Message to display that a player is not online.
    offline-error: "&cNorimas Ã…Â¾aidÃ„â€”jas neprisijungÃ„â„¢s."

    # Message to show that the command cannot be executed via console.
    player-command-usage: "&cÃ…Â i komanda buvo iÃ…Â¡jungta per konsolÃ„â„¢."

    # Message to show that a command can only be executed by the console.
    console-command-usage: "&cÃ…Â iÃ„â€¦ komandÃ„â€¦ galima naudoti tik per konsolÃ„â„¢."

    # Message shown when the plugin is reloaded.
    plugin-reload-message: "&ePapildinys sÃ„â€”kmingai perkrautas."

    # Message shown when the function of a command is disabled.
    command-function-disabled: "&cKomandos funkcija {0} yra iÃ…Â¡jungta."

    # Message sent when a database operation has not been successfully performed.
    database-error: "&cDeja, mums nepavyko uÃ…Â¾baigti Ã…Â¡ios operacijos. PraÃ…Â¡au, pabandykite dar kartÃ„â€¦. [SQL FAIL]"

  other-messages:
    # Hover message: /login.
    hover-message-login: "&7SpustelÃ„â€”kite Ã„Âia, kad uÃ…Â¾baigtumÃ„â€”te komandÃ„â€¦ ir greitai prisijungtumÃ„â€”te."

    # Hover message: /register.
    hover-message-register: "&7SpustelÃ„â€”kite Ã„Âia, kad uÃ…Â¾baigtumÃ„â€”te komandÃ„â€¦ ir greitai uÃ…Â¾registruotumÃ„â€”te."

    # Command usage: /login
    message-login: "&eNaudokite komandÃ„â€¦ &7/login <slaptaÃ…Â¾odis>&e."

    # Command usage: /register
    message-register: "&eNaudokite komandÃ„â€¦ &7/register <slaptaÃ…Â¾odis> <slaptaÃ…Â¾odis>&e."

    # Command usage: /changepassword
    message-changepassword: "&eNaudokite komandÃ„â€¦ &7/changepassword <dabartinis slaptaÃ…Â¾odis> <naujas slaptaÃ…Â¾odis>&e."

    # Command usage: /checkprofile
    message-verify: "&eNaudokite komandÃ„â€¦ &7/checkprofile <Ã…Â¾aidÃ„â€”jas>&e."

    # Command usage: /unregister
    message-unregister: "&eNaudokite komandÃ„â€¦ &7/unregister <dabartinis slaptaÃ…Â¾odis>&e."
