#  ________  ___  __    ___       ________  ________  ___  ________     
# |\   __  \|\  \|\  \ |\  \     |\   __  \|\   ____\|\  \|\   ___  \  
# \ \  \|\  \ \  \/  /|\ \  \    \ \  \|\  \ \  \___|\ \  \ \  \\ \  \ 
#  \ \   ____\ \   ___  \ \  \    \ \  \\\  \ \  \  __\ \  \ \  \\ \  \ 
#   \ \  \___|\ \  \\ \  \ \  \____\ \  \\\  \ \  \|\  \ \  \ \  \\ \  \
#    \ \__\    \ \__\\ \__\ \_______\ \_______\ \_______\ \__\ \__\\ \__\
#     \|__|     \|__| \|__|\|_______|\|_______|\|_______|\|__|\|__| \|__|

# Official Website: https://www.pumpkiiings.com
# Discord: https://www.pumpkiiings.com/discord

# Tradotto in Italiano da Peppe73
# Spigot: https://www.spigotmc.org/members/peppe73.693388/

version: "1.1"

Messages:
  Title:
    # Messaggio inviato prima del login
    before-login:
      title: "&a&lBenvenuto!"
      subtitle: "&7Per il login usa: /login <tua password>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Messaggio inviato prima della registrazione
    before-register:
      title: "&a&lBenvenuto!"
      subtitle: "&7Per registrarti usa: /register <tua password> <tua password>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Messaggio inviato dopo il login
    after-login:
      title: ""
      subtitle: "&aHai effettuato il log in con successo!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Messaggio inviato dopo la registrazione
    after-register:
      title: ""
      subtitle: "&aTi sei registrato con successo!"
      delays:
        start: 0
        duration: 60
        end: 6

        bedrock-auto-login:
        title: "&a&lWelcome!"
        subtitle: "&7Logged in as &eBedrock&7."
        delays:
          start: 0
          duration: 30
          end: 6
      premium-auto-login:
        title: "&a&lWelcome!"
        subtitle: "&7Logged in as &6Premium&7."
        delays:
          start: 0
          duration: 30
          end: 6

  delay-kick:
    # Messaggio inviato quando un utente impiega molto tempo per registrarsi
    register-kick: "&cHai impiegato troppo tempo per registrarti."

    # Messaggio inviato quando un utente impiega molto tempo per accedere
    login-kick: "&cHai impiegato troppo tempo per accedere."

  successful-operations:
    # Messaggio quando un utente scambia la propria password
    password-changed: "&aLa tua password Ã¨ stata cambiata con successo."

    # Messaggio inviato quando un utente accede con successo
    successful-login: "&aHai effettuato l'accesso con successo."

    # Messaggio inviato quando un utente si registra correttamente
    successful-register: "&aTi sei registrato con successo."

    # Messaggio inviato quando un giocatore si annulla con successo
    unregister-kick: "&cHai annullato la registrazione con successo."

  kick-messages:
    # Messaggio quando un giocatore tenta di accedere al server con una piccola differenza nel nickname
    nick-already-registered: "&cNon puoi entrare con questo nickname {0}&r\n&r&cQuesto nome utente Ã¨ giÃ  registrato come {1}&r\n&r\n&r&cPer entrare, devi usare il tuo nickname senza maiuscole/minuscole"

    # Messaggio inviato quando un utente perde molte volte
    failed-many-times: "&cPassword errata."

    # Messaggio inviato quando la password inserita non Ã¨ corretta
    incorrect-password: "&cPassword errata. Per favore riprova."

    # Messaggio inviato quando un giocatore inserisce un nickname non valido.
    invalid-nickname: "&cSpiacente, stai usando un nickname non valido."

  error-messages:
    # Messaggio inviato quando sei giÃ  loggato.
    already-login: "&cSei giÃ  loggato."

    # Messaggio inviato quando Ã¨ giÃ  stato registrato un nickname.
    already-registered: "&cQuesto nickname Ã¨ giÃ  stato registrato."

    # Messaggio inviato quando un nickname non Ã¨ stato ancora registrato.
    not-registered: "&cQuesto nickname Ã¨ ancora libero."

    # Messaggio inviato quando la password inserita non Ã¨ uguale alla seconda
    passwords-dont-match: "&cLe password non sono le stesse."

    # Messaggio inviato quando un giocatore tenta di cambiare la password inserendo la stessa password di quella corrente
    password-same-as-old: "&cLa password inserita Ã¨ la stessa di quella corrente."

    # Messaggio inviato quando la password inserita Ã¨ troppo grande
    password-too-large: "&cLa password inserita Ã¨ troppo lunga."

    # Messaggio inviato quando la password inserita Ã¨ troppo piccola
    password-too-small: "&cLa password inserita Ã¨ troppo corta."
    insecure-password: "&cYour password is too weak. It must include numbers, uppercase, lowercase, and symbols."
    change-password-enforced: "&cFor security reasons, you must update your password right now using &e/changepassword&c."

    # Messaggio quando un giocatore non possiede l'autorizzazione richiesta
    insufficient-permissions: "&cNon sei autorizzato ad eseguire questo comando."

    # Messaggio per cacciare un giocatore ora online
    already-online: "&cQuesto giocatore Ã¨ giÃ  online."

    # Messaggio per mostrare che il comando non puÃ² essere eseguito tramite console
    player-command-usage: "&cQuesto comando Ã¨ stato disattivato tramite console."

    # Messaggio mostrato quando il plugin viene ricaricato.
    plugin-reload-message: "&ePlugin ricaricato con successo."

    # Messaggio inviato quando un'operazione sul database non Ã¨ stata eseguita correttamente
    database-error: "&cSpiacenti, non Ã¨ stato possibile completare questa operazione. Per favore riprova. [SQL FAIL]"

  other-messages:
    # Messaggio inviato per o utilizzando il comando /login
    message-login: "&eUsa il comando /login <password>"

    # Messaggio inviato per o utilizzando il comando /register
    message-register: "&eUsa il comando /register <password> <password>"

    # Messaggio inviato per o utilizzando il comando /mudarsenha
    message-changepassword: "&eUsa il comando /changepassword <current password> <new password>"

    # Messaggio inviato per utilizzare il /unregister command
    message-unregister: "&eUsa il comando /unregister <current password>"
