# Configuración de PkAuth Addon
# Puedes usar códigos de colores hexadecimales o formato MiniMessage (Paper).

ui:
  scoreboard:
    title: "<u><b><color:#C8B470><shadow:#322D1C:1><u><b>AUTH</b></u></shadow></color></b></u>"
    lines:
      - ""
      - "<color:#FFFFFF><shadow:#404040:1>Estado:</shadow></color>"
      - "<color:#FF0000><shadow:#400000:1> ✘ No Autenticado</shadow></color>"
      - ""
      - "<color:#FFFFFF><shadow:#404040:1>Registrate con:</shadow></color>"
      - " <color:#FFE300><shadow:#403900:1>/register <c> <c></shadow></color>"
      - ""
      - "<color:#FFFFFF><shadow:#404040:1>Ingresa con:</shadow></color>"
      - " <color:#FFE300><shadow:#403900:1>/login <contraseña></shadow></color>"
      - ""
      - "<color:#D3BC6F><shadow:#352F1C:1>mc.liric.xyz</shadow></color>"
  
  scoreboard-authenticated:
    title: "<u><b><color:#C8B470><shadow:#322D1C:1><u><b>AUTH</b></u></shadow></color></b></u>"
    lines:
      - ""
      - "<color:#FFFFFF><shadow:#404040:1>Estado:</shadow></color>"
      - "<color:#03FF00><shadow:#014000:1> ✔ Autenticado</shadow></color>"
      - ""
      - "<color:#FF9500><shadow:#402500:1>⏳ Esperando el proxy...</shadow></color>"
      - ""
      - "<color:#D3BC6F><shadow:#352F1C:1>mc.liric.xyz</shadow></color>"

  tablist:
    header:
      - ""
      - "<#FFAA00><b>BIENVENIDO A PKLOGIN</b>"
      - "<#AAAAAA>Por favor, inicia sesión para jugar."
      - ""
    footer:
      - ""
      - "<#AAAAAA>IP: <#FFFFFF>play.tuserver.com"
      - "<#AAAAAA>Discord: <#55FF55>discord.gg/tuserver"
      - ""

auth-world:
  # Si es true, cancela el daño y PvP entre jugadores en el mundo auth
  cancel-pvp: true
  # Si es true, los jugadores no autenticados no se ven entre sí ni en el tab
  hide-unauthenticated: true

messages:
  player_not_found: "<#FF5555>Jugador no encontrado."
  config_reloaded: "<#55FF55>Configuración de PkAuth recargada correctamente."
  # Mensaje que se muestra en el chat cuando entras al auth ya estando logueado.
  # Soporta MiniMessage. Placeholder: %player%
  already-authenticated: |-
    <#FFD700><b>¡Ups!</b> <#AAAAAA>Aparentemente estás en el eterno vacío otra vez... Bueno, al menos puedes jugar <#55FF55>Piedra Papel o Tijera <#AAAAAA>contra el servidor o un jugador con <#FFFF55>/rps jugador/bot
    <#AAAAAA>o jugar el juego de la serpiente con <#FFFF55>/snake play

snake:
  messages:
    actionbar_exit: "<#AAAAAA>Presiona <#55FF55><b>Shift</b> <#AAAAAA>para salir del juego"
    win: "<#55FF55>¡Ganaste! Puntaje: %score%"
    game_over: "<#FF5555>¡Juego Terminado! Puntaje: %score%"
  sounds:
    eat: "ENTITY_PLAYER_BURP"
    win: "UI_TOAST_CHALLENGE_COMPLETE"
    game_over: "BLOCK_AMETHYST_BLOCK_BREAK"
